In [12]:
from sqlalchemy import create_engine
import pandas as pd
ENGINE = create_engine(
    f"postgresql://postgres:Wtcantfw36c!@dandypdb01fl:5432/smdb")

In [13]:
schema_name = 'data'
table_name = 'edna_wetlab_report'

In [26]:
wetlab = pd.read_sql(f'select * from "{schema_name}"."{table_name}"', ENGINE)
flowcell = pd.read_sql(f'select * from "{schema_name}"."flowcell"', ENGINE)

In [27]:
wetlab = wetlab.dropna(subset='library_id')

In [28]:
wetlab[wetlab.duplicated(subset='library_id', keep=False)].sort_values(by='library_id')

,wet_lab_customer_name,wet_lab_order_date,wet_lab_order_id,wet_lab_no,wet_lab_total_sample_quantity,wet_lab_robot_sample_rack_name,robot_sample_rack_barcode,robot_sample_rack_position,robot_sample_id,archive_sample_id,...,wet_lab_project_done_date,database_insert_by,upload_sheet,database_insert_datetime_utc,fastq_file_id,upload_uuid,library_prep_method,prod_res_path,wet_lab_comp_id,short_edna_concentration
5383,Mikkel Winther Pedersen,2022-05-31,SS0014,48,46,Rack10,LVL900026679,F08,ExrNTC22060201,ExrNTC,...,2022-07-11,upload_user,Wetlab Summary_Export to Magnus.txt,2024-04-29 15:18:03.396137+02:00,LV3003061567-ExrNTC22060201-ExrNTC,1db07c31-1548-4127-89a5-d4dda3518a41,double strand DNA Library Method,/projects/caeg/data/production/*/*/*/LV3003061...,eDNA220601144_LV3003061567_CSIWQ,None
5382,Mikkel Winther Pedersen,2022-05-31,SS0014,48,46,Rack10,LVL900026679,F08,ExrNTC22060201,ExrNTC,...,2022-07-11,upload_user,Wetlab Summary_Export to Magnus.txt,2024-04-29 15:18:03.396137+02:00,LV3003061567-ExrNTC22060201-ExrNTC,1db07c31-1548-4127-89a5-d4dda3518a41,double strand DNA Library Method,/projects/caeg/data/production/*/*/*/LV3003061...,eDNA220601144_LV3003061567_MTVCY,None
5065,Mikkel Winther Pedersen,2022-04-27,SS0010,16,46,Rack17,LVL900026675,D03,LV7000630703,CGG-3-016501,...,2023-08-22,upload_user,Wetlab Summary_Export to Magnus.txt,2024-04-29 15:18:03.396137+02:00,LV7001838917-LV7000630703-CGG-3-016501,1db07c31-1548-4127-89a5-d4dda3518a41,double strand DNA Library Method,/projects/caeg/data/production/*/*/*/LV7001838...,eDNA220531016_LV7001838917_WR2FE,None
992,Mikkel Winther Pedersen,2022-04-27,SS0010,16,46,Rack17,LVL900026675,D03,LV7000630703,CGG-3-016501,...,2023-08-22,upload_user,Wetlab Summary_Export to Magnus.txt,2024-04-29 15:18:03.396137+02:00,None,1db07c31-1548-4127-89a5-d4dda3518a41,double strand DNA Library Method,None,eDNA220531016_LV7001838917_eDNALib012-pool,None
6645,Kurt Kjær,2023-03-07,SS0036,48,138,Rack53,LVL900114397,F08,ExrNTC23030701,ExrNTC,...,2023-05-03,upload_user,Wetlab Summary_Export to Magnus.txt,2024-04-29 15:18:03.396137+02:00,LV7001884396-ExrNTC23030701-ExrNTC,1db07c31-1548-4127-89a5-d4dda3518a41,double strand DNA Library Method,/projects/caeg/data/production/*/*/*/LV7001884...,eDNA230330048_LV7001884396_AIH6N,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,Kurt Kjær,2023-12-14,SS0083,144,396,Rack216,LVL600052967,F08,ExrNTC23121402,ExrNTC,...,2024-03-26,upload_user,Wetlab Summary_Export to Magnus.txt,2024-04-29 15:18:03.396137+02:00,LV7008960531-ExrNTC23121402-ExrNTC,1db07c31-1548-4127-89a5-d4dda3518a41,single strand DNA Library Method,/projects/caeg/data/production/*/*/*/LV7008960...,eDNA240116144_LV7008960531_SS4ED,None
8646,Kurt Kjær,2023-12-14,SS0083,144,396,Rack216,LVL600052967,F08,ExrNTC23121402,ExrNTC,...,2024-03-26,upload_user,Wetlab Summary_Export to Magnus.txt,2024-04-29 15:18:03.396137+02:00,LV7008960531-ExrNTC23121402-ExrNTC,1db07c31-1548-4127-89a5-d4dda3518a41,single strand DNA Library Method,/projects/caeg/data/production/*/*/*/LV7008960...,eDNA240116144_LV7008960531_LSMVU,None
8647,Kurt Kjær,2023-12-14,SS0083,144,396,Rack216,LVL600052967,F08,ExrNTC23121402,ExrNTC,...,2024-03-26,upload_user,Wetlab Summary_Export to Magnus.txt,2024-04-29 15:18:03.396137+02:00,LV7008960531-ExrNTC23121402-ExrNTC,1db07c31-1548-4127-89a5-d4dda3518a41,single strand DNA Library Method,/projects/caeg/data/production/*/*/*/LV7008960...,eDNA240116144_LV7008960531_X4BL7,None
8785,Kurt Kjær,2023-12-14,SS0083,240,396,Rack218,LVL600052942,F08,ExrNTC23121403,ExrNTC,...,2024-03-26,upload_user,Wetlab Summary_Export to Magnus.txt,2024-04-29 15:18:03.396137+02:00,LV7008961083-ExrNTC23121403-ExrNTC,1db07c31-1548-4127-89a5-d4dda3518a41,single strand DNA Library Method,/projects/caeg/data/production/*/*/*/LV7008961...,eDNA240131048_LV7008961083_QW4F7,None
8786,Kurt Kjær,2023-12-14,SS0083,240,396,Rack218,LVL600052942,F08,ExrNTC23121403,ExrNTC,...,2024-03-26,upload_user,Wetlab Summary_Export to Magnus.txt,2024-04-29 15:18:03.396137+02:00,LV7008961083-ExrNTC23121403-ExrNTC,1db07c31-1548-4127-89a5-d4dda3518a41,single strand DNA Library Method,/projects/caeg/data/production/*/*/*/LV7008961...,eDNA240131048_LV7008961083_YWZC4,None

In [31]:
df_1 = wetlab.query('fastq_file_id == "LV7008960531-ExrNTC23121402-ExrNTC"')

In [32]:
df_1

,wet_lab_customer_name,wet_lab_order_date,wet_lab_order_id,wet_lab_no,wet_lab_total_sample_quantity,wet_lab_robot_sample_rack_name,robot_sample_rack_barcode,robot_sample_rack_position,robot_sample_id,archive_sample_id,...,wet_lab_project_done_date,database_insert_by,upload_sheet,database_insert_datetime_utc,fastq_file_id,upload_uuid,library_prep_method,prod_res_path,wet_lab_comp_id,short_edna_concentration
2961,Kurt Kjær,2023-12-14,SS0083,144,396,Rack216,LVL600052967,F08,ExrNTC23121402,ExrNTC,...,2024-03-26,upload_user,Wetlab Summary_Export to Magnus.txt,2024-04-29 15:18:03.396137+02:00,LV7008960531-ExrNTC23121402-ExrNTC,1db07c31-1548-4127-89a5-d4dda3518a41,single strand DNA Library Method,/projects/caeg/data/production/*/*/*/LV7008960...,eDNA240116144_LV7008960531_SS4ED,None
8646,Kurt Kjær,2023-12-14,SS0083,144,396,Rack216,LVL600052967,F08,ExrNTC23121402,ExrNTC,...,2024-03-26,upload_user,Wetlab Summary_Export to Magnus.txt,2024-04-29 15:18:03.396137+02:00,LV7008960531-ExrNTC23121402-ExrNTC,1db07c31-1548-4127-89a5-d4dda3518a41,single strand DNA Library Method,/projects/caeg/data/production/*/*/*/LV7008960...,eDNA240116144_LV7008960531_LSMVU,None
8647,Kurt Kjær,2023-12-14,SS0083,144,396,Rack216,LVL600052967,F08,ExrNTC23121402,ExrNTC,...,2024-03-26,upload_user,Wetlab Summary_Export to Magnus.txt,2024-04-29 15:18:03.396137+02:00,LV7008960531-ExrNTC23121402-ExrNTC,1db07c31-1548-4127-89a5-d4dda3518a41,single strand DNA Library Method,/projects/caeg/data/production/*/*/*/LV7008960...,eDNA240116144_LV7008960531_X4BL7,None

In [34]:
df_2 = flowcell.query('fastq_file_id == "LV7008960531-ExrNTC23121402-ExrNTC"')

In [ ]:
m = pd.merge(df_1, df_2, on='fastq_file_id', how='outer')  # Will cause cross join becasuse of multiple lanes and runs on different flowcells. TODO: Fix

In [39]:
df_2

,flowcell_lane,wet_lab_project_name,fastq_file_id,dna_barcode_sequence,pf_clusters,percent_of_the_flow_cell_lane,percent_perfect_dna_barcode,percent_one_mismatch_dna_barcode,flowcell_yield_mbases,percent_pf_clusters,...,mean_quality_score,flowcell_id,flowcell_clusters_raw_sum,flowcell_clusters_pf_sum,flowcell_yield_mbases_sum,database_insert_by,upload_sheet,database_insert_datetime_utc,upload_uuid,fastq_path
2063,1,RocsDeglaciation,LV7008960531-ExrNTC23121402-ExrNTC,AATCCAATTG+CCTCTACATG,32436,0.0,95.22,4.78,7,100.0,...,34.60,H3C37DSX7,15320088576,11727283913,2368911,upload_user,laneBarcode_X4BL7.html,2024-04-29 08:46:27.237556+02:00,a3df60df-a9e0-4e62-947f-90f24b2b0c43,/datasets/caeg_fastq/*/*H3C37DSX7*/*/LV7008960...
2114,2,RocsDeglaciation,LV7008960531-ExrNTC23121402-ExrNTC,AATCCAATTG+CCTCTACATG,30794,0.0,94.75,5.25,6,100.0,...,34.51,H3C37DSX7,15320088576,11727283913,2368911,upload_user,laneBarcode_X4BL7.html,2024-04-29 08:46:27.237556+02:00,a3df60df-a9e0-4e62-947f-90f24b2b0c43,/datasets/caeg_fastq/*/*H3C37DSX7*/*/LV7008960...
2164,3,RocsDeglaciation,LV7008960531-ExrNTC23121402-ExrNTC,AATCCAATTG+CCTCTACATG,31495,0.0,94.86,5.14,6,100.0,...,34.59,H3C37DSX7,15320088576,11727283913,2368911,upload_user,laneBarcode_X4BL7.html,2024-04-29 08:46:27.237556+02:00,a3df60df-a9e0-4e62-947f-90f24b2b0c43,/datasets/caeg_fastq/*/*H3C37DSX7*/*/LV7008960...
2215,4,RocsDeglaciation,LV7008960531-ExrNTC23121402-ExrNTC,AATCCAATTG+CCTCTACATG,33231,0.0,95.28,4.72,7,100.0,...,34.73,H3C37DSX7,15320088576,11727283913,2368911,upload_user,laneBarcode_X4BL7.html,2024-04-29 08:46:27.237556+02:00,a3df60df-a9e0-4e62-947f-90f24b2b0c43,/datasets/caeg_fastq/*/*H3C37DSX7*/*/LV7008960...
10192,1,RocsDeglaciation,LV7008960531-ExrNTC23121402-ExrNTC,AATCCAATTG+CCTCTACATG,27905,0.0,96.83,3.17,6,100.0,...,35.51,H32VNDSX7,15320088576,12595959036,2544384,upload_user,SS4ED_laneBarcode.html,2024-05-06 14:47:35.608298+02:00,2fa1d3eb-20e4-4fa6-b647-cf57634d67ae,/datasets/caeg_fastq/*/*H32VNDSX7*/*/LV7008960...
10242,2,RocsDeglaciation,LV7008960531-ExrNTC23121402-ExrNTC,AATCCAATTG+CCTCTACATG,28308,0.0,96.86,3.14,6,100.0,...,35.54,H32VNDSX7,15320088576,12595959036,2544384,upload_user,SS4ED_laneBarcode.html,2024-05-06 14:47:35.608298+02:00,2fa1d3eb-20e4-4fa6-b647-cf57634d67ae,/datasets/caeg_fastq/*/*H32VNDSX7*/*/LV7008960...
10293,3,RocsDeglaciation,LV7008960531-ExrNTC23121402-ExrNTC,AATCCAATTG+CCTCTACATG,27772,0.0,96.87,3.13,6,100.0,...,35.52,H32VNDSX7,15320088576,12595959036,2544384,upload_user,SS4ED_laneBarcode.html,2024-05-06 14:47:35.608298+02:00,2fa1d3eb-20e4-4fa6-b647-cf57634d67ae,/datasets/caeg_fastq/*/*H32VNDSX7*/*/LV7008960...
10344,4,RocsDeglaciation,LV7008960531-ExrNTC23121402-ExrNTC,AATCCAATTG+CCTCTACATG,28060,0.0,97.05,2.95,6,100.0,...,35.53,H32VNDSX7,15320088576,12595959036,2544384,upload_user,SS4ED_laneBarcode.html,2024-05-06 14:47:35.608298+02:00,2fa1d3eb-20e4-4fa6-b647-cf57634d67ae,/datasets/caeg_fastq/*/*H32VNDSX7*/*/LV7008960...

In [38]:
df_1

,wet_lab_customer_name,wet_lab_order_date,wet_lab_order_id,wet_lab_no,wet_lab_total_sample_quantity,wet_lab_robot_sample_rack_name,robot_sample_rack_barcode,robot_sample_rack_position,robot_sample_id,archive_sample_id,...,wet_lab_project_done_date,database_insert_by,upload_sheet,database_insert_datetime_utc,fastq_file_id,upload_uuid,library_prep_method,prod_res_path,wet_lab_comp_id,short_edna_concentration
2961,Kurt Kjær,2023-12-14,SS0083,144,396,Rack216,LVL600052967,F08,ExrNTC23121402,ExrNTC,...,2024-03-26,upload_user,Wetlab Summary_Export to Magnus.txt,2024-04-29 15:18:03.396137+02:00,LV7008960531-ExrNTC23121402-ExrNTC,1db07c31-1548-4127-89a5-d4dda3518a41,single strand DNA Library Method,/projects/caeg/data/production/*/*/*/LV7008960...,eDNA240116144_LV7008960531_SS4ED,None
8646,Kurt Kjær,2023-12-14,SS0083,144,396,Rack216,LVL600052967,F08,ExrNTC23121402,ExrNTC,...,2024-03-26,upload_user,Wetlab Summary_Export to Magnus.txt,2024-04-29 15:18:03.396137+02:00,LV7008960531-ExrNTC23121402-ExrNTC,1db07c31-1548-4127-89a5-d4dda3518a41,single strand DNA Library Method,/projects/caeg/data/production/*/*/*/LV7008960...,eDNA240116144_LV7008960531_LSMVU,None
8647,Kurt Kjær,2023-12-14,SS0083,144,396,Rack216,LVL600052967,F08,ExrNTC23121402,ExrNTC,...,2024-03-26,upload_user,Wetlab Summary_Export to Magnus.txt,2024-04-29 15:18:03.396137+02:00,LV7008960531-ExrNTC23121402-ExrNTC,1db07c31-1548-4127-89a5-d4dda3518a41,single strand DNA Library Method,/projects/caeg/data/production/*/*/*/LV7008960...,eDNA240116144_LV7008960531_X4BL7,None

In [43]:
m[['seqc_tube_tag', 'flowcell_id', 'flowcell_lane', 'fastq_file_id', 'library_concentration', 'pf_clusters']]

,seqc_tube_tag,flowcell_id,flowcell_lane,fastq_file_id,library_concentration,pf_clusters
0,SS4ED,H3C37DSX7,1,LV7008960531-ExrNTC23121402-ExrNTC,0.12,32436
1,SS4ED,H3C37DSX7,2,LV7008960531-ExrNTC23121402-ExrNTC,0.12,30794
2,SS4ED,H3C37DSX7,3,LV7008960531-ExrNTC23121402-ExrNTC,0.12,31495
3,SS4ED,H3C37DSX7,4,LV7008960531-ExrNTC23121402-ExrNTC,0.12,33231
4,SS4ED,H32VNDSX7,1,LV7008960531-ExrNTC23121402-ExrNTC,0.12,27905
5,SS4ED,H32VNDSX7,2,LV7008960531-ExrNTC23121402-ExrNTC,0.12,28308
6,SS4ED,H32VNDSX7,3,LV7008960531-ExrNTC23121402-ExrNTC,0.12,27772
7,SS4ED,H32VNDSX7,4,LV7008960531-ExrNTC23121402-ExrNTC,0.12,28060
8,LSMVU,H3C37DSX7,1,LV7008960531-ExrNTC23121402-ExrNTC,0.12,32436
9,LSMVU,H3C37DSX7,2,LV7008960531-ExrNTC23121402-ExrNTC,0.12,30794
10,LSMVU,H3C37DSX7,3,LV7008960531-ExrNTC23121402-ExrNTC,0.12,31495
11,LSMVU,H3C37DSX7,4,LV7008960531-ExrNTC23121402-ExrNTC,0.12,33231
12,LSMVU,H32VNDSX7,1,LV7008960531-ExrNTC23121402-ExrNTC,0.12,27905
13,LSMVU,H32VNDSX7,2,LV7008960531-ExrNTC23121402-ExrNTC,0.12,28308
14,LSMVU,H32VNDSX7,3,LV7008960531-ExrNTC23121402-ExrNTC,0.12,27772
15,LSMVU,H32VNDSX7,4,LV7008960531-ExrNTC23121402-ExrNTC,0.12,28060
16,X4BL7,H3C37DSX7,1,LV7008960531-ExrNTC23121402-ExrNTC,0.12,32436
17,X4BL7,H3C37DSX7,2,LV7008960531-ExrNTC23121402-ExrNTC,0.12,30794
18,X4BL7,H3C37DSX7,3,LV7008960531-ExrNTC23121402-ExrNTC,0.12,31495
19,X4BL7,H3C37DSX7,4,LV7008960531-ExrNTC23121402-ExrNTC,0.12,33231
20,X4BL7,H32VNDSX7,1,LV7008960531-ExrNTC23121402-ExrNTC,0.12,27905
21,X4BL7,H32VNDSX7,2,LV7008960531-ExrNTC23121402-ExrNTC,0.12,28308
22,X4BL7,H32VNDSX7,3,LV7008960531-ExrNTC23121402-ExrNTC,0.12,27772
23,X4BL7,H32VNDSX7,4,LV7008960531-ExrNTC23121402-ExrNTC,0.12,28060

In [50]:
wetlab.query('seqc_tube_tag == "X4BL7"').apply(lambda col: col.unique())

wet_lab_customer_name                                                               [Kurt Kjær]
wet_lab_order_date                                                        [2023-12-14 00:00:00]
wet_lab_order_id                                                                       [SS0083]
wet_lab_no                                    [146, 147, 161, 144, 145, 148, 149, 150, 151, ...
wet_lab_total_sample_quantity                                                             [396]
wet_lab_robot_sample_rack_name                                               [Rack217, Rack216]
robot_sample_rack_barcode                                          [LVL600052940, LVL600052967]
robot_sample_rack_position                    [B01, C01, E03, F08, A01, D01, E01, F01, A02, ...
robot_sample_id                               [LV6000198663, LV6000198793, LV6000198811, Exr...
archive_sample_id                             [LV3005274907, LV3005274890, LV3005274857, Exr...
edna_lysate_plate_id                                                              [eDNALys076#]
edna_lysate_position                          [B07, C07, A09, H06, A07, D07, E07, F07, G07, ...
lysis_date                                                                [2024-01-15 00:00:00]
edna_plate_id                                                                     [eDNAExr089#]
edna_plate_position                           [B07, C07, A09, H06, A07, D07, E07, F07, G07, ...
edna_id                                       [eDNA240116146, eDNA240116147, eDNA240116161, ...
total_edna_concentration                                                                  [0.0]
wet_lab_cleanup_date                                                      [2024-01-16 00:00:00]
wet_lab_customer_attention_to_extraction                                                 [None]
library_plate_id                                                                [ssDNALib0013#]
library_plate_barcode                                                            [LVL800028679]
library_plate_position                        [B07, C07, A09, H06, A07, D07, E07, F07, G07, ...
library_id                                    [LV7008960458, LV7008960470, LV7008960444, LV7...
library_concentration                         [104.77, 82.48, 73.62, 0.12, 47.61, 15.85, 13....
library_peak_size                             [188.0, 196.0, nan, 187.0, 189.0, 191.0, 190.0...
library_leftover_volume                       [24.27, 22.73, 21.85, 29.0, 28.74, 26.22, 25.7...
library_qc_result                                             [Qualified, N.A., Low Risk, None]
library_start_date                                                        [2024-01-29 00:00:00]
wet_lab_ct                                    [11.0, 11.14, 11.69, 23.3, 12.47, 13.17, 11.3,...
qpcr_date                                                                 [2024-02-02 00:00:00]
idt_index_no                                  [UDP0146, UDP0147, UDP0161, UDP0144, UDP0145, ...
i7_bases_in_adapter                           [AATTGCTGCG, TAAGGAACGT, AGATGGAATT, CAATTGGAT...
i5_bases_in_adapter                           [ATTCCGCTAT, GACCGCTGTG, CTTCAGTTAC, CATGTAGAG...
pcr_cycle                                                                                [12.0]
indexing_pcr_date                                                         [2024-02-05 00:00:00]
library_cleanup_date                                                      [2024-02-05 00:00:00]
library_qc_date                                                           [2024-02-12 00:00:00]
wet_lab_customer_attention_to_library_prep                                               [None]
seqc_tube_tag                                                                           [X4BL7]
dna_pooled                                                   [60.0, 0.12, 30.0, 0.31, 0.0, 1.0]
expected_sequencing_data                                          [230.0, 0.0, 115.0, 1.0, 4.0]
wet_lab_submitting_date                                                            [26/02/2024]
return_dna                                                                              [false]
return_library                                                                          [false]
return_pool                                                                             [false]
pool_to_seqc                                                                             [true]
wet_lab_project_done_date                                                 [2024-03-26 00:00:00]
database_insert_by                                                                [upload_user]
upload_sheet                                              [Wetlab Summary_Export to Magnus.txt]
database_insert_datetime_utc                                 [2024-04-29 15:18:03.396137+02:00]
fastq_file_id                                 [LV7008960458-LV6000198663-LV3005274907, LV700...
upload_uuid                                              [1db07c31-1548-4127-89a5-d4dda3518a41]
library_prep_method                                          [single strand DNA Library Method]
prod_res_path                                 [/projects/caeg/data/production/*/*/*/LV700896...
wet_lab_comp_id                               [eDNA240116146_LV7008960458_X4BL7, eDNA2401161...
short_edna_concentration                                                                 [None]
dtype: object