In [5]:
%env PGPASSWORD=5J8DhII0RRsPW1

env: PGPASSWORD=5J8DhII0RRsPW1

In [13]:
import pandas as pd
from sqlalchemy import create_engine

In [14]:
ENGINE = create_engine(
    f"postgresql://postgres:Wtcantfw36c!@dandypdb01fl:5432/aedna_metadata_test")

In [15]:
cgg_path = r'c:\Users\glj523\Downloads\LAST_VERSION_OF_CGG3_20240410.xlsx'
cgg_df = pd.read_excel(cgg_path, sheet_name='Sediment_Water', dtype=object)

In [22]:
unnamed_cols = cgg_df.columns[cgg_df.columns.str.startswith('Unnamed')]

In [27]:
cgg_df.dropna(how='all', axis='columns').columns

Index(['CGG ID', 'Museum ID/sample ID', 'Lab no.', 'Stock sample left',
       'Extraction#', 'Extraction date', 'Kind of Library', 'Library date',
       'Intern Provider', 'Sample type', 'Depth', 'height (m) asl.',
       'Material type', 'Sampled as', 'Sample size',
       'Depositional environment', 'Age', 'Geological age', 'Site',
       'Site info', 'City/town/location', 'State/province/region', 'Country',
       'Continent', 'Lat', 'Lon', 'GPS', 'Sample Provider',
       'Museum/Institution', 'Contact info', 'Date collected', 'Date recieved',
       'Date returned', 'Sample location', 'Extraction location',
       'In care of ', 'Date out', 'Project name', 'Supervisor',
       'Analyses history', 'GenBank ref#', 'Publications', 'References',
       'Notes', 'Thawed up', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47',
       'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51',
       'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 57',
       'Unnamed: 62', 'Unnamed: 74'],
      dtype='object')

In [16]:
cgg_df.to_sql(name='cgg_sediment_water',
              con=ENGINE,
              schema='test_1',
              if_exists='replace',
              index=True,
              index_label='cgg3_smdb_id')

217

In [17]:
len(cgg_df)

20857

In [1]:
lal = None
if len(lal) > 1:
    print('helleo')

TypeError: object of type 'NoneType' has no len()

In [2]:
from geopy.distance import geodesic
from utils import queries
from constants.db_connections import ENGINE_READ_ONLY

In [11]:
df = queries.get_geo_distances_from_db_table(29.88603, 
                                        120.375051, 
                                        'field_sample', 
                                        'test_1', 
                                        'longitude', 
                                        'latitude',
                                        distance_threshold=1000,
                                        db_engine=ENGINE_READ_ONLY)

In [13]:
df

,field_sample_id,field_sample_country_ocean,field_sample_site_name,latitude,longitude,field_sample_sample_date,field_sample_sample_provider,field_sample_running_project_title,field_sampling_depth_discrete,field_sampling_interval_to,...,site_grid_elev,site_grid_latitude,site_grid_longitude,field_sample_parent_id,field_sample_label_informal,field_sample_type_in_storage_at_gm,permit_for_dna_analysis,field_sample_environment_secondary,clean_id,distance
0,CGG_3_014928,China,Rice lake 16.12,29.88603,120.375051,2024-10-08,Yucheng Wang,CalsbergRice,None,None,...,None,None,None,CGG_3_014928M,RiceLake16.12AM,sediment block,True,None,CGG3014928,0.0
1,CGG_3_014930,China,Rice lake 16.12,29.88603,120.375051,2024-10-08,Yucheng Wang,CalsbergRice,None,None,...,None,None,None,CGG_3_014930M,RiceLake16.12AM,sediment block,True,None,CGG3014930,0.0
2,CGG_3_014933,China,Rice lake 16.12,29.88603,120.375051,2024-10-08,Yucheng Wang,CalsbergRice,None,None,...,None,None,None,CGG_3_014933M,RiceLake16.12AM,sediment block,True,None,CGG3014933,0.0
3,CGG_3_014936,China,Rice lake 16.12,29.88603,120.375051,2024-10-08,Yucheng Wang,CalsbergRice,None,None,...,None,None,None,CGG_3_014936M,RiceLake16.12AM,sediment block,True,None,CGG3014936,0.0
4,CGG_3_014939,China,Rice lake 16.12,29.88603,120.375051,2024-10-08,Yucheng Wang,CalsbergRice,None,None,...,None,None,None,CGG_3_014939M,RiceLake16.12AM,sediment block,True,None,CGG3014939,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,CGG_3_015224,China,Rice lake 16.12,29.88603,120.375051,2024-10-08,Yucheng Wang,CalsbergRice,None,None,...,None,None,None,CGG_3_015224M,RiceLake16.12DM,sediment block,True,None,CGG3015224,0.0
57,CGG_3_015230,China,Rice lake 16.12,29.88603,120.375051,2024-10-08,Yucheng Wang,CalsbergRice,None,None,...,None,None,None,CGG_3_015230M,RiceLake16.12DM,sediment block,True,None,CGG3015230,0.0
58,CGG_3_015236,China,Rice lake 16.12,29.88603,120.375051,2024-10-08,Yucheng Wang,CalsbergRice,None,None,...,None,None,None,CGG_3_015236M,RiceLake16.12DM,sediment block,True,None,CGG3015236,0.0
59,CGG_3_015242,China,Rice lake 16.12,29.88603,120.375051,2024-10-08,Yucheng Wang,CalsbergRice,None,None,...,None,None,None,CGG_3_015242M,RiceLake16.12DM,sediment block,True,None,CGG3015242,0.0
60,CGG_3_015256,China,Rice lake 16.12,29.88603,120.375051,2024-10-08,Yucheng Wang,CalsbergRice,None,None,...,None,None,None,CGG_3_015256M,RiceLake16.12DM,sediment block,True,None,CGG3015256,0.0

In [16]:
df[~df.duplicated(subset=['latitude', 'longitude'])]

,field_sample_id,field_sample_country_ocean,field_sample_site_name,latitude,longitude,field_sample_sample_date,field_sample_sample_provider,field_sample_running_project_title,field_sampling_depth_discrete,field_sampling_interval_to,...,site_grid_elev,site_grid_latitude,site_grid_longitude,field_sample_parent_id,field_sample_label_informal,field_sample_type_in_storage_at_gm,permit_for_dna_analysis,field_sample_environment_secondary,clean_id,distance
0,CGG_3_014928,China,Rice lake 16.12,29.88603,120.375051,2024-10-08,Yucheng Wang,CalsbergRice,None,None,...,None,None,None,CGG_3_014928M,RiceLake16.12AM,sediment block,True,None,CGG3014928,0.0

In [ ]:
df[['latitude', 'longitude']].unique()a

AttributeError: 'DataFrame' object has no attribute 'unique'

In [6]:
def is_similar_location(lat1, lon1, lat2, lon2, threshold=0.01):
    return geodesic((lat1, lon1), (lat2, lon2)).km <= threshold

In [7]:
coords = [12.34124, 100.301044, 12.34124, 90.301044]

In [10]:
is_similar_location(*coords)

False

In [2]:
import os
p = os.path.join('jse', 'kkaf', 'file.sdd')

os.path.dirname(p)

'jse\\kkaf'

In [1]:
from math import isclose

In [4]:
isclose(101.4032, 101.4033, abs_tol=0.001)

True

In [42]:

import os, sys
from sqlalchemy import create_engine
import pandas as pd
from constants.db_names.names import data 
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from constants.misc_constants import RESPONSIBLE_UPLOADERS

DATABASE_CONFIG_READ_ONLY = {
    'host': 'dandypdb01fl',
    'dbname': 'aedna_metadata_test',
    'port': '5432',
    'user': 'read_user',
    'password': r'mv5&8B%eKuoE8D',
}
ENGINE_READ_ONLY = create_engine(
    f"postgresql://{DATABASE_CONFIG_READ_ONLY['user']}:{DATABASE_CONFIG_READ_ONLY['password']}@{DATABASE_CONFIG_READ_ONLY['host']}:{DATABASE_CONFIG_READ_ONLY['port']}/{DATABASE_CONFIG_READ_ONLY['dbname']}")

# Email details
sender_email = "glj523@dandyweb01fl.unicph.domain"
xihan_email = "magnus.johannsen@sund.ku.dk"
jesper_email = "magnus.johannsen@sund.ku.dk"
subject = "Missing metadata"
body = "The sample metadata database (SMDB) is missing data from you. See attached document to see the missing IDs."
message = MIMEMultipart()
message["From"] = sender_email
message["Subject"] = subject
message.attach(MIMEText(body, "plain"))

input = [
    'LV7001885838',
    'LV7008887632',
    'LV7009026245',
    'LV7008886642',
    'LV7001884279',
    'LV7001884009',
    'LV7001884028',
    'test'
]

lib_pk_col_name = data.edna_wetlab_report.library_id()
lib_fk_col_name = data.edna_wetlab_report.robot_sample_id()

rs_pk_col_name = data.edna_robot_sample.robot_sample_id()
rs_fk_col_name = data.edna_robot_sample.archivesampleid()

as_pk_col_name = data.edna_archive_sample.archivesampleid()
as_fk_col_name = data.edna_archive_sample.field_sample_id()

md_fk_col_name = data.master_depth.depth_id()
md_pk_col_name = data.master_depth.archive_sample_id()
master_depth_col_name = data.master_depth.master_depth()


adm_pk_col_name = data.age_depth_model.depth_id()
mean_age_col_name = data.age_depth_model.mean()

fs_pk_col_name = data.field_sample.field_sample_id()

wr_table_name = data.edna_wetlab_report()
rs_table_name = data.edna_robot_sample()
as_table_name = data.edna_archive_sample()
fs_table_name = data.field_sample()
md_table_name = data.master_depth()
adm_table_name = data.age_depth_model()


query = lambda library_ids: f'''
WITH filtered_table AS (
    select distinct {lib_pk_col_name}, {lib_fk_col_name} from {wr_table_name} 
    where {lib_pk_col_name} in {library_ids})
select 
filtered_table.{lib_pk_col_name}, 
ers.{rs_pk_col_name}, 
eas.{as_pk_col_name}, 
md.{master_depth_col_name},
adm.{mean_age_col_name},
fs.{fs_pk_col_name}
FROM filtered_table
left JOIN {rs_table_name} ers on filtered_table.{lib_fk_col_name} = ers.{rs_pk_col_name}
left join {as_table_name} eas on ers.{rs_fk_col_name} = eas.{as_pk_col_name}
left join {md_table_name} md on eas.{as_pk_col_name} = md.{md_pk_col_name}
left join {adm_table_name} adm on md.{md_fk_col_name} = adm.{adm_pk_col_name}
left join {fs_table_name} fs on eas.{as_fk_col_name} = fs.{fs_pk_col_name}
order by {lib_pk_col_name};
'''

df = pd.read_sql(query(tuple(input)), ENGINE_READ_ONLY)

_map = {wr_table_name: lib_pk_col_name,
        rs_table_name: rs_pk_col_name,
        as_table_name: as_pk_col_name,
        md_table_name: master_depth_col_name,
        adm_table_name: mean_age_col_name,
        fs_table_name: fs_pk_col_name,
        data.flowcell(): data.flowcell.fastq_file_id(),
        data.seq_sample_sheet(): data.seq_sample_sheet.fastq_file_id()}
RESPONSIBLE_UPLOADERS = {key: [_map[ele] for ele in val] for key, val in RESPONSIBLE_UPLOADERS.items()}

send_reminder_to = []
for key, val in RESPONSIBLE_UPLOADERS.items():
    cols = list(set(val) & set(df.columns))
    if len(cols) > 0:  
        if df[cols].isna().any().any():
            send_reminder_to.append(key)

In [19]:
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

# Email details
sender_email = "you@yourdomain.com"
receiver_email = "recipient@example.com"
subject = "Email with Attachment"
body = "This email contains an attachment sent via Postfix."

# File to attach
file_path = "/path/to/your/file.txt"
file_name = "file.txt"  # Name to appear in the email

# Create the email
message = MIMEMultipart()
message["From"] = sender_email
message["To"] = receiver_email
message["Subject"] = subject

# Attach the email body
message.attach(MIMEText(body, "plain"))

# Attach the file
with open(file_path, "rb") as file:
    part = MIMEBase("application", "octet-stream")
    part.set_payload(file.read())

# Encode the file for email
encoders.encode_base64(part)
part.add_header(
    "Content-Disposition",
    f"attachment; filename={file_name}",
)

message.attach(part)

# Send the email via Postfix
try:
    with smtplib.SMTP("localhost", 25) as server:  # Postfix typically listens on port 25
        server.send_message(message)
        print("Email sent successfully with attachment!")
except Exception as e:
    print(f"Error: {e}")

In [83]:
for i, column in enumerate(id_columns):
    
    print(column)
    print(df.query(f'{column}.isna()').iloc[:, :df.columns.get_loc(column)])

robot_sample_id
     library_id
0  LV7001884009
1  LV7001884028
3  LV7001885838
5  LV7008887632
6  LV7009026245
archive_sample_id
     library_id robot_sample_id
0  LV7001884009            None
1  LV7001884028            None
2  LV7001884279    lv7001308345
3  LV7001885838            None
5  LV7008887632            None
6  LV7009026245            None
field_sample_id
     library_id robot_sample_id archive_sample_id
0  LV7001884009            None              None
1  LV7001884028            None              None
2  LV7001884279    lv7001308345              None
3  LV7001885838            None              None
4  LV7008886642    LV6000199939      LV3006006216
5  LV7008887632            None              None
6  LV7009026245            None              None

In [66]:
df.columns.get_loc('robot_sample_id')

1

In [63]:
for index, row in df.iterrows():
    print(row[1])

None
None
lv7001308345
None
LV6000199939
None
None

C:\Users\glj523\AppData\Local\Temp\ipykernel_19264\3319070448.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(row[1])

In [32]:
for column in df.columns:
    if df[column].isna().any():
        print(column)
        # Send mail to responsible uploader

robot_sample_id
archive_sample_id
field_sample_id

True

In [13]:
tables = {}
for table in list(data.__dict__.keys()):
    if not table.startswith('_'):
        q = f'select * from {data()}.{table}'
        df = pd.read_sql(q, con=ENGINE_READ_ONLY)
        tables[table] = df

In [15]:
data.__dict__

mappingproxy({'__module__': 'constants.db_names.names',
              '_db_id': 1,
              'edna_robot_sample': constants.db_names.names.data.edna_robot_sample,
              'age_depth_model': constants.db_names.names.data.age_depth_model,
              'master_depth': constants.db_names.names.data.master_depth,
              'field_sample_types': constants.db_names.names.data.field_sample_types,
              'cgg_animal_plant': constants.db_names.names.data.cgg_animal_plant,
              'country_ocean': constants.db_names.names.data.country_ocean,
              'field_sample_environment_types': constants.db_names.names.data.field_sample_environment_types,
              'edna_wetlab_report': constants.db_names.names.data.edna_wetlab_report,
              'flowcell': constants.db_names.names.data.flowcell,
              'cgg_sediment_water': constants.db_names.names.data.cgg_sediment_water,
              'adna_wetlab_report': constants.db_names.names.data.adna_wetlab_report,
              'field_sample_material_type': constants.db_names.names.data.field_sample_material_type,
              'field_sample_context_types': constants.db_names.names.data.field_sample_context_types,
              'edna_archive_sample': constants.db_names.names.data.edna_archive_sample,
              'initials_translator': constants.db_names.names.data.initials_translator,
              'seq_sample_sheet': constants.db_names.names.data.seq_sample_sheet,
              'field_sample': constants.db_names.names.data.field_sample,
              'top_unknown_seq_barcodes': constants.db_names.names.data.top_unknown_seq_barcodes,
              '__doc__': None})

In [ ]:
how = 'outer'

merge_keys = {'field_sample': 'field_sample_id',
              'edna_archive_sample': ['archive_sample_id', 'field_sample_id'],
              'edna_robot_sample': ''}

tables['field_sample']['field_sample_id'] = tables['field_sample_id'].str.lower()


merged = (
    tables['field_sample']
    .merge(tables['edna_archive_sample'], on='field_sample_id', how=how)
    .merge(tables['edna_archive_sample'], on='field_sample_id', how=how)
    .merge(tables['edna_archive_sample'], on='field_sample_id', how=how)
    .merge(tables['edna_archive_sample'], on='field_sample_id', how=how)
    .merge(tables['edna_archive_sample'], on='field_sample_id', how=how)
    .merge(tables['edna_archive_sample'], on='field_sample_id', how=how)
)