In [1]:
from sqlalchemy import create_engine

In [2]:
ENGINE = create_engine(
    f"postgresql://postgres:Wtcantfw36c!@dandypdb01fl:5432/aedna_metadata_test")

In [3]:
import pandas as pd

In [71]:
q1 = '''
SELECT s.sample_name, sdt.data_key, COALESCE(NULLIF(sd.value, 'None'), NULL) AS value
FROM test_1.sample s
JOIN test_1.sample_data sd ON s.sample_id = sd.sample_id
JOIN test_1.sample_data_type sdt ON sd.sample_data_type_id = sdt.sample_data_type_id
WHERE sdt.data_section != 'general_stats'
ORDER BY 1
'''

q1 = pd.read_sql(q1, ENGINE)

In [72]:
q1

,sample_name,data_key,value
0,Lib_LV3000765846_collapsed,samtools_stats__average_quality,36.3
1,Lib_LV3000765846_collapsed,nonpareil_low_complexity__nonpareil_LRstar,115798167826.6313
2,Lib_LV3000765846_collapsed,nonpareil_low_complexity__nonpareil_star,90
3,Lib_LV3000765846_collapsed,samtools_stats__total_first_fragment_length,432800085.0
4,Lib_LV3000765846_collapsed,samtools_stats__last_fragments,0.0
...,...,...,...
1404727,Lib_LV7009027909_L004_singleton,fastqc_trimmed__total_deduplicated_percentage,68.55071633283374
1404728,Lib_LV7009027909_L004_singleton,fastqc_trimmed__per_tile_sequence_quality,pass
1404729,Lib_LV7009027909_L004_singleton,fastqc_trimmed__per_base_sequence_content,fail
1404730,Lib_LV7009027909_L004_singleton,fastqc_trimmed__per_sequence_quality_scores,pass
1404731,Lib_LV7009027909_L004_singleton,fastqc_trimmed__Sequence length,30-101

In [6]:
q2 = '''
SELECT DISTINCT sdt.data_key
FROM test_1.sample s
JOIN test_1.sample_data sd ON s.sample_id = sd.sample_id
JOIN test_1.sample_data_type sdt ON sd.sample_data_type_id = sdt.sample_data_type_id
WHERE data_section != 'general_stats'
ORDER BY 1
'''
q2 = pd.read_sql(q2, ENGINE)

In [69]:

data = pd.read_csv('test.csv')

pivoted_df = data.pivot(index='sample_name', columns='data_key', values='value')

# Reset the index to make sample_name a regular column (optional)
pivoted_df = pivoted_df.reset_index()

In [80]:
ex = q1[q1.duplicated(subset=['sample_name', 'data_key'], keep=False)].sort_values(by=['sample_name', 'data_key'])

In [73]:
pivoted_df = q1.pivot(index='sample_name', columns='data_key', values='value')

# Reset the index to make sample_name a regular column (optional)
pivoted_df = pivoted_df.reset_index()

ValueError: Index contains duplicate entries, cannot reshape

In [67]:
pivoted_df

data_key,sample_name,nonpareil_low_complexity__nonpareil_AL,nonpareil_low_complexity__nonpareil_C,nonpareil_low_complexity__nonpareil_LR,nonpareil_low_complexity__nonpareil_LRstar,nonpareil_low_complexity__nonpareil_R,nonpareil_low_complexity__nonpareil_col,nonpareil_low_complexity__nonpareil_diversity,nonpareil_low_complexity__nonpareil_file,nonpareil_low_complexity__nonpareil_kappa,...,samtools_stats__reads_mapped,samtools_stats__reads_mapped_and_paired,samtools_stats__reads_paired,samtools_stats__reads_properly_paired,samtools_stats__reads_unmapped,samtools_stats__sequences,samtools_stats__supplementary_alignments,samtools_stats__total_first_fragment_length,samtools_stats__total_last_fragment_length,samtools_stats__total_length
0,Lib_LV3000765846_collapsed,78.256,0.6713,11513560103.952,115798167826.6313,147126867,#9A6759,21.4734,stats/reads/nonpareil/low_complexity/Lib_LV300...,0.6466,...,6717886.0,0.0,0.0,0.0,0.0,6717886.0,0.0,432800085.0,0.0,432800085.0

In [64]:
(data['sample_name'] + data['data_key']).duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
dtype: bool

In [41]:
piv = q1.pivot(columns='data_key', values='value')

In [44]:
piv.columns.name = None

In [45]:
piv

,bowtie2__overall_alignment_rate,bowtie2__total_reads,bowtie2__unpaired_aligned_multi,bowtie2__unpaired_aligned_none,bowtie2__unpaired_aligned_one,bowtie2__unpaired_total,fastp__adapter_cutting,fastp__command,fastp__filtering_result,fastp__insert_size,...,samtools_stats__reads_paired_percent,samtools_stats__reads_properly_paired,samtools_stats__reads_properly_paired_percent,samtools_stats__reads_unmapped,samtools_stats__reads_unmapped_percent,samtools_stats__sequences,samtools_stats__supplementary_alignments,samtools_stats__total_first_fragment_length,samtools_stats__total_last_fragment_length,samtools_stats__total_length
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,432800085.0,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1404727,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404728,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404729,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404730,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404731,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
piv.insert(loc=0, column='sample_name', value=q1['sample_name'])

In [47]:
piv

,sample_name,bowtie2__overall_alignment_rate,bowtie2__total_reads,bowtie2__unpaired_aligned_multi,bowtie2__unpaired_aligned_none,bowtie2__unpaired_aligned_one,bowtie2__unpaired_total,fastp__adapter_cutting,fastp__command,fastp__filtering_result,...,samtools_stats__reads_paired_percent,samtools_stats__reads_properly_paired,samtools_stats__reads_properly_paired_percent,samtools_stats__reads_unmapped,samtools_stats__reads_unmapped_percent,samtools_stats__sequences,samtools_stats__supplementary_alignments,samtools_stats__total_first_fragment_length,samtools_stats__total_last_fragment_length,samtools_stats__total_length
0,Lib_LV3000765846_collapsed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Lib_LV3000765846_collapsed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Lib_LV3000765846_collapsed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Lib_LV3000765846_collapsed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,432800085.0,NaN,NaN
4,Lib_LV3000765846_collapsed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1404727,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404728,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404729,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404730,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404731,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
q1

,sample_name,data_key,value
0,Lib_LV3000765846_collapsed,samtools_stats__average_quality,36.3
1,Lib_LV3000765846_collapsed,nonpareil_low_complexity__nonpareil_LRstar,115798167826.6313
2,Lib_LV3000765846_collapsed,nonpareil_low_complexity__nonpareil_star,90
3,Lib_LV3000765846_collapsed,samtools_stats__total_first_fragment_length,432800085.0
4,Lib_LV3000765846_collapsed,samtools_stats__last_fragments,0.0
...,...,...,...
1404727,Lib_LV7009027909_L004_singleton,fastqc_trimmed__total_deduplicated_percentage,68.55071633283374
1404728,Lib_LV7009027909_L004_singleton,fastqc_trimmed__per_tile_sequence_quality,pass
1404729,Lib_LV7009027909_L004_singleton,fastqc_trimmed__per_base_sequence_content,fail
1404730,Lib_LV7009027909_L004_singleton,fastqc_trimmed__per_sequence_quality_scores,pass
1404731,Lib_LV7009027909_L004_singleton,fastqc_trimmed__Sequence length,30-101

In [53]:
piv[(piv["sample_name"] == 'Lib_LV7009027909_L004_singleton')]

,sample_name,bowtie2__overall_alignment_rate,bowtie2__total_reads,bowtie2__unpaired_aligned_multi,bowtie2__unpaired_aligned_none,bowtie2__unpaired_aligned_one,bowtie2__unpaired_total,fastp__adapter_cutting,fastp__command,fastp__filtering_result,...,samtools_stats__reads_paired_percent,samtools_stats__reads_properly_paired,samtools_stats__reads_properly_paired_percent,samtools_stats__reads_unmapped,samtools_stats__reads_unmapped_percent,samtools_stats__sequences,samtools_stats__supplementary_alignments,samtools_stats__total_first_fragment_length,samtools_stats__total_last_fragment_length,samtools_stats__total_length
1404710,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404711,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404712,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404713,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404714,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404715,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404716,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404717,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404718,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404719,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404720,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404721,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404722,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404723,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404724,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404725,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404726,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404727,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404728,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404729,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404730,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404731,Lib_LV7009027909_L004_singleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
dict(piv[(piv["sample_name"] == 'Lib_LV7009027909_L004_singleton')].iloc[0][1:-1].dropna().items())

{'fastqc_trimmed__%GC': '50.0'}

In [49]:
bad_vals = []
test_len = len(set(piv["sample_name"]))
big_validation = True
if big_validation:
        print("Starting big validation. This might take while...")
        for i, sample_name in enumerate(set(piv["sample_name"])):
            if i%100 == 0:
                print(f"validatet {i} out of {test_len}")

            for key, val in piv[(piv["sample_name"] == sample_name)].iloc[0][1:-1].dropna().items():
                val2 = str(q1[(q1["sample_name"] == sample_name) & (q1["data_key"] == key)]["value"].iloc[0])
                if val != val2:
                    bad_vals.append(sample_name)
                    print("found bad val: ", sample_name)
        
        assert len(bad_vals) == 0, f"all bad vals: {bad_vals}"
            
        print(f'Done validating {i+1} out of {test_len} rows.')

Starting big validation. This might take while...
validatet 0 out of 97521
validatet 100 out of 97521
validatet 200 out of 97521
validatet 300 out of 97521
validatet 400 out of 97521
validatet 500 out of 97521
validatet 600 out of 97521
validatet 700 out of 97521
validatet 800 out of 97521
validatet 900 out of 97521
validatet 1000 out of 97521
validatet 1100 out of 97521
validatet 1200 out of 97521
validatet 1300 out of 97521

KeyboardInterrupt: