In [9]:
from pathlib import Path
import sys
import os

def find_project_root():
    path = Path(os.getcwd()).resolve()
    while path != path.root:
        if (path / 'very_rootsy_file.txt').exists():
            return path
        path = path.parent
    return None  # Project root not found

project_root = find_project_root()

sys.path.append(str(project_root))

In [10]:
from sqlalchemy import create_engine

import table_merges
ENGINE = create_engine(
    f"postgresql://postgres:Wtcantfw36c!@dandypdb01fl:5432/aedna_metadata_test")
import pandas as pd
report_meta = "select * from report_meta where report_meta_key = 'config_output_dir' or report_meta_key ='config_creation_date'"
report_meta = pd.read_sql(report_meta, ENGINE)
report_meta_piv = report_meta.pivot(columns='report_meta_key', index='report_id', values='report_meta_value')
report_meta_piv.columns.name = None
report_meta_piv = report_meta_piv.reset_index()
multiqc_data = '''
            SELECT s.sample_name, sdt.data_key, NULLIF(sd.value, 'None') AS value, sd.report_id
            FROM sample_data sd
            JOIN sample_data_type sdt ON sdt.sample_data_type_id = sd.sample_data_type_id
            JOIN sample s ON sd.sample_id = s.sample_id
            WHERE sdt.data_section != 'general_stats'; 
        '''
multiqc_data = pd.read_sql(multiqc_data, ENGINE)
mega_meta = table_merges.outer_merge('test_1', ENGINE)

In [2]:
multiqc_data

,sample_name,data_key,value,report_id
0,Lib_LV7008953920_collapsed,samtools_stats__filtered_sequences,0.0,55
1,Lib_LV7008953920_collapsed,samtools_stats__total_last_fragment_length,0.0,55
2,Lib_LV7008953920_collapsed,samtools_stats__bases_mapped_(cigar),336430120.0,55
3,Lib_LV7008953920_collapsed,samtools_stats__reads_QC_failed,0.0,55
4,Lib_LV7008953920_collapsed,samtools_stats__reads_paired,0.0,55
...,...,...,...,...
1517728,Lib_LV7009022595_L004,fastp__filtering_result,"{'passed_filter_reads': 59727954, 'corrected_r...",1998
1517729,Lib_LV7009022595_L004,fastp__insert_size,"{'peak': 0, 'unknown': 1367682, 'histogram': [...",1998
1517730,Lib_LV7009022595_L004,fastp__polyx_trimming,"{'total_polyx_trimmed_reads': 1372147, 'polyx_...",1998
1517731,Lib_LV7009022595_L004,fastp__adapter_cutting,"{'adapter_trimmed_reads': 47388784, 'adapter_t...",1998
1517732,Lib_LV7009022595_L004,fastp__read1_before_filtering,"{'total_reads': 38459520, 'total_bases': 38844...",1998

In [4]:
pivoted_df = multiqc_data.pivot(index=['sample_name', 'report_id'], columns='data_key', values='value')
pivoted_df.columns.name = None
# Reset the index to make sample_name a regular column (optional)
pivoted_df = pivoted_df.reset_index()
mega_qc = pivoted_df.merge(report_meta_piv, on='report_id', how='inner')
assert len(pivoted_df) == len(mega_qc)
for i in range(100):
    test_data = mega_qc.sample(100)[['report_id', 'config_creation_date', 'config_output_dir']].drop_duplicates('report_id')
    assert (report_meta_piv[report_meta_piv['report_id'].isin(test_data['report_id'])].sort_values('report_id').reset_index(drop=True).astype(str) == test_data.sort_values('report_id').reset_index(drop=True).astype(str)).all().all()
mega_qc = mega_qc.rename(columns={'config_creation_date': 'binf_multiqc_datetime', 'config_output_dir': 'path_to_binf_multiqc_report'})
mega_qc.insert(loc=0, column='library_id', value=mega_qc['sample_name'].str.split('_').apply(lambda x: x[1])) 
mega_qc.insert(loc=1, column='lane_read_trimtype_etc', value=mega_qc['sample_name'].str.split('_').apply(lambda x: '_'.join(x[2:]))) 
mega_qc = mega_qc.drop(columns=['sample_name', 'report_id'])
col_to_move = mega_qc.pop('path_to_binf_multiqc_report')
mega_qc.insert(2, 'path_to_binf_multiqc_report', col_to_move)
col_to_move = mega_qc.pop('binf_multiqc_datetime')
mega_qc.insert(3, 'binf_multiqc_datetime', col_to_move)
giga_table = mega_meta.merge(mega_qc, on='library_id', how='outer')

In [5]:
mega_qc

,library_id,lane_read_trimtype_etc,path_to_binf_multiqc_report,binf_multiqc_datetime,bowtie2__overall_alignment_rate,bowtie2__total_reads,bowtie2__unpaired_aligned_multi,bowtie2__unpaired_aligned_none,bowtie2__unpaired_aligned_one,bowtie2__unpaired_total,...,samtools_stats__reads_paired_percent,samtools_stats__reads_properly_paired,samtools_stats__reads_properly_paired_percent,samtools_stats__reads_unmapped,samtools_stats__reads_unmapped_percent,samtools_stats__sequences,samtools_stats__supplementary_alignments,samtools_stats__total_first_fragment_length,samtools_stats__total_last_fragment_length,samtools_stats__total_length
0,LV3000765846,L001,/maps/projects/caeg/data/production/LV3/000/76...,"2024-12-04, 07:28 CET",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LV3000765846,L001_R1,/maps/projects/caeg/data/production/LV3/000/76...,"2024-12-04, 07:28 CET",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LV3000765846,L001_R2,/maps/projects/caeg/data/production/LV3/000/76...,"2024-12-04, 07:28 CET",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LV3000765846,L001_collapsed,/maps/projects/caeg/data/production/LV3/000/76...,"2024-12-04, 07:28 CET",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LV3000765846,L001_singleton,/maps/projects/caeg/data/production/LV3/000/76...,"2024-12-04, 07:28 CET",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107300,LV7009027909,collapsed.refseq_vertebrate_other.4-of-8,/maps/projects/caeg/data/production/LV7/009/02...,"2024-12-10, 04:48 CET",0.01,264366056,8065,264352504,5487,264366056,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107301,LV7009027909,collapsed.refseq_vertebrate_other.5-of-8,/maps/projects/caeg/data/production/LV7/009/02...,"2024-12-10, 04:48 CET",0.0,264366056,8371,264354665,3020,264366056,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107302,LV7009027909,collapsed.refseq_vertebrate_other.6-of-8,/maps/projects/caeg/data/production/LV7/009/02...,"2024-12-10, 04:48 CET",0.0,264366056,5724,264355781,4551,264366056,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107303,LV7009027909,collapsed.refseq_vertebrate_other.7-of-8,/maps/projects/caeg/data/production/LV7/009/02...,"2024-12-10, 04:48 CET",0.0,264366056,6435,264356801,2820,264366056,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107304,LV7009027909,collapsed.refseq_vertebrate_other.8-of-8,/maps/projects/caeg/data/production/LV7/009/02...,"2024-12-10, 04:48 CET",0.01,264366056,9594,264348146,8316,264366056,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
test_cols = mega_qc.columns
for lib_id in mega_qc.library_id.unique():    
    test1 = mega_qc[
        mega_qc['library_id'] == lib_id
    ][test_cols].astype(str).sort_values(
        by=['path_to_binf_multiqc_report', 'lane_read_trimtype_etc']
    ).reset_index(drop=True)
    test2 = giga_table[
        giga_table['library_id'] == lib_id
    ][test_cols].astype(str).sort_values(
        by=['path_to_binf_multiqc_report', 'lane_read_trimtype_etc']
    ).reset_index(drop=True)

    try:
        assert (test1 == test2).all().all()
    except Exception:
        raise Exception(f'{lib_id}')

Exception: LV7008865054

In [122]:
mega_qc['lane_read_trimtype_etc'].unique()

array(['L001', 'L001_R1', 'L001_R2', 'L001_collapsed', 'L001_singleton',
       'L002', 'L002_R1', 'L002_R2', 'L002_collapsed', 'L002_singleton',
       'L003', 'L003_R1', 'L003_R2', 'L003_collapsed', 'L003_singleton',
       'L004', 'L004_R1', 'L004_R2', 'L004_collapsed', 'L004_singleton',
       'collapsed', 'collapsed.norway.1-of-7', 'collapsed.norway.2-of-7',
       'collapsed.norway.3-of-7', 'collapsed.norway.4-of-7',
       'collapsed.norway.5-of-7', 'collapsed.norway.6-of-7',
       'collapsed.norway.7-of-7', 'collapsed.nt.1-of-9',
       'collapsed.nt.2-of-9', 'collapsed.nt.3-of-9',
       'collapsed.nt.4-of-9', 'collapsed.nt.5-of-9',
       'collapsed.nt.6-of-9', 'collapsed.nt.7-of-9',
       'collapsed.nt.8-of-9', 'collapsed.nt.9-of-9',
       'collapsed.polar.1-of-1', 'collapsed.polar_b3.1-of-1',
       'collapsed.polar_other.1-of-1',
       'collapsed.refseq_archaea_fungi_virus.1-of-1',
       'collapsed.refseq_invertebrate.1-of-3',
       'collapsed.refseq_invertebrate.2-of-3',
       'collapsed.refseq_invertebrate.3-of-3',
       'collapsed.refseq_mitochondrion.1-of-1',
       'collapsed.refseq_plant.1-of-5', 'collapsed.refseq_plant.2-of-5',
       'collapsed.refseq_plant.3-of-5', 'collapsed.refseq_plant.4-of-5',
       'collapsed.refseq_plant.5-of-5', 'collapsed.refseq_plastid.1-of-1',
       'collapsed.refseq_protozoa.1-of-1',
       'collapsed.refseq_vertebrate_mammal.1-of-10',
       'collapsed.refseq_vertebrate_mammal.10-of-10',
       'collapsed.refseq_vertebrate_mammal.2-of-10',
       'collapsed.refseq_vertebrate_mammal.3-of-10',
       'collapsed.refseq_vertebrate_mammal.4-of-10',
       'collapsed.refseq_vertebrate_mammal.5-of-10',
       'collapsed.refseq_vertebrate_mammal.6-of-10',
       'collapsed.refseq_vertebrate_mammal.7-of-10',
       'collapsed.refseq_vertebrate_mammal.8-of-10',
       'collapsed.refseq_vertebrate_mammal.9-of-10',
       'collapsed.refseq_vertebrate_other.1-of-8',
       'collapsed.refseq_vertebrate_other.2-of-8',
       'collapsed.refseq_vertebrate_other.3-of-8',
       'collapsed.refseq_vertebrate_other.4-of-8',
       'collapsed.refseq_vertebrate_other.5-of-8',
       'collapsed.refseq_vertebrate_other.6-of-8',
       'collapsed.refseq_vertebrate_other.7-of-8',
       'collapsed.refseq_vertebrate_other.8-of-8',
       'collapsed.bact_archaea.1-of-1'], dtype=object)

In [142]:
res = {}
key1 = str({'fastqc_trimmed__Encoding', 'fastqc_trimmed__%GC', 'fastqc_raw__basic_statistics', 'library_id', 'fastqc_raw__sequence_duplication_levels', 'fastqc_trimmed__median_sequence_length', 'fastqc_raw__avg_sequence_length', 'fastqc_raw__Sequences flagged as poor quality', 'fastqc_raw__Encoding', 'fastqc_trimmed__Total Sequences', 'fastqc_raw__per_base_sequence_quality', 'fastqc_trimmed__per_base_sequence_quality', 'fastqc_trimmed__File type', 'fastqc_raw__Total Bases', 'fastqc_raw__median_sequence_length', 'fastqc_raw__overrepresented_sequences', 'fastqc_raw__per_base_sequence_content', 'binf_multiqc_datetime', 'fastqc_raw__sequence_length_distribution', 'fastqc_raw__per_sequence_quality_scores', 'fastqc_trimmed__per_base_sequence_content', 'fastqc_trimmed__Total Bases', 'fastqc_raw__adapter_content', 'fastqc_trimmed__per_sequence_quality_scores', 'fastqc_trimmed__per_tile_sequence_quality', 'path_to_binf_multiqc_report', 'fastqc_trimmed__per_base_n_content', 'fastqc_trimmed__adapter_content', 'fastqc_raw__Total Sequences', 'fastqc_trimmed__overrepresented_sequences', 'fastqc_raw__total_deduplicated_percentage', 'fastqc_raw__File type', 'lane_read_trimtype_etc', 'fastqc_trimmed__avg_sequence_length', 'fastqc_trimmed__sequence_length_distribution', 'fastqc_trimmed__per_sequence_gc_content', 'fastqc_trimmed__sequence_duplication_levels', 'fastqc_raw__per_base_n_content', 'fastqc_trimmed__total_deduplicated_percentage', 'fastqc_raw__per_tile_sequence_quality', 'fastqc_trimmed__Sequence length', 'fastqc_trimmed__Sequences flagged as poor quality', 'fastqc_trimmed__Filename', 'fastqc_raw__%GC', 'fastqc_raw__Sequence length', 'fastqc_raw__Filename', 'fastqc_trimmed__basic_statistics', 'fastqc_raw__per_sequence_gc_content'})

In [143]:
res[key1] = 'l001'

In [144]:
res

{"{'fastqc_trimmed__Encoding', 'fastqc_trimmed__%GC', 'fastqc_raw__basic_statistics', 'library_id', 'fastqc_raw__sequence_duplication_levels', 'fastqc_trimmed__median_sequence_length', 'fastqc_raw__avg_sequence_length', 'fastqc_raw__Sequences flagged as poor quality', 'fastqc_raw__Encoding', 'fastqc_trimmed__Total Sequences', 'fastqc_raw__per_base_sequence_quality', 'fastqc_trimmed__per_base_sequence_quality', 'fastqc_trimmed__File type', 'fastqc_raw__Total Bases', 'fastqc_raw__median_sequence_length', 'fastqc_raw__overrepresented_sequences', 'fastqc_raw__per_base_sequence_content', 'binf_multiqc_datetime', 'fastqc_raw__sequence_length_distribution', 'fastqc_raw__per_sequence_quality_scores', 'fastqc_trimmed__per_base_sequence_content', 'fastqc_trimmed__Total Bases', 'fastqc_raw__adapter_content', 'fastqc_trimmed__per_sequence_quality_scores', 'fastqc_trimmed__per_tile_sequence_quality', 'path_to_binf_multiqc_report', 'fastqc_trimmed__adapter_content', 'fastqc_raw__Filename', 'fastqc_raw__Total Sequences', 'fastqc_trimmed__overrepresented_sequences', 'fastqc_raw__total_deduplicated_percentage', 'fastqc_raw__File type', 'lane_read_trimtype_etc', 'fastqc_trimmed__avg_sequence_length', 'fastqc_trimmed__sequence_length_distribution', 'fastqc_trimmed__per_sequence_gc_content', 'fastqc_trimmed__sequence_duplication_levels', 'fastqc_raw__per_base_n_content', 'fastqc_trimmed__total_deduplicated_percentage', 'fastqc_raw__per_tile_sequence_quality', 'fastqc_trimmed__Sequence length', 'fastqc_trimmed__Sequences flagged as poor quality', 'fastqc_trimmed__Filename', 'fastqc_raw__%GC', 'fastqc_raw__Sequence length', 'fastqc_trimmed__per_base_n_content', 'fastqc_trimmed__basic_statistics', 'fastqc_raw__per_sequence_gc_content'}": 'l001'}

In [149]:
res = {}
for ele in mega_qc['lane_read_trimtype_etc'].unique():
    try:
        cols_with_data = str(set(mega_qc[mega_qc['lane_read_trimtype_etc']==ele].dropna(how='all', axis='columns').columns.sort_values()))
        if cols_with_data not in res:
            res[cols_with_data] = [str(ele)]
        else:
            res[cols_with_data].append(str(ele))
    except:
        raise Exception(f'{ele}, {cols_with_data}')

In [ ]:
mega_qc

In [153]:
mega_qc

,library_id,lane_read_trimtype_etc,path_to_binf_multiqc_report,binf_multiqc_datetime,bowtie2__overall_alignment_rate,bowtie2__total_reads,bowtie2__unpaired_aligned_multi,bowtie2__unpaired_aligned_none,bowtie2__unpaired_aligned_one,bowtie2__unpaired_total,...,samtools_stats__reads_paired_percent,samtools_stats__reads_properly_paired,samtools_stats__reads_properly_paired_percent,samtools_stats__reads_unmapped,samtools_stats__reads_unmapped_percent,samtools_stats__sequences,samtools_stats__supplementary_alignments,samtools_stats__total_first_fragment_length,samtools_stats__total_last_fragment_length,samtools_stats__total_length
0,LV3000765846,L001,/maps/projects/caeg/data/production/LV3/000/76...,"2024-08-09, 20:00 CEST",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LV3000765846,L001_R1,/maps/projects/caeg/data/production/LV3/000/76...,"2024-08-09, 20:00 CEST",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LV3000765846,L001_R2,/maps/projects/caeg/data/production/LV3/000/76...,"2024-08-09, 20:00 CEST",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LV3000765846,L001_collapsed,/maps/projects/caeg/data/production/LV3/000/76...,"2024-08-09, 20:00 CEST",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LV3000765846,L001_singleton,/maps/projects/caeg/data/production/LV3/000/76...,"2024-08-09, 20:00 CEST",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98766,LV7009027909,collapsed.refseq_vertebrate_other.4-of-8,/maps/projects/caeg/data/production/LV7/009/02...,"2024-08-15, 17:42 CEST",0.01,264352557,7987,264339130,5440,264352557,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98767,LV7009027909,collapsed.refseq_vertebrate_other.5-of-8,/maps/projects/caeg/data/production/LV7/009/02...,"2024-08-15, 17:42 CEST",0.0,264352557,8281,264341301,2975,264352557,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98768,LV7009027909,collapsed.refseq_vertebrate_other.6-of-8,/maps/projects/caeg/data/production/LV7/009/02...,"2024-08-15, 17:42 CEST",0.0,264352557,5706,264342309,4542,264352557,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98769,LV7009027909,collapsed.refseq_vertebrate_other.7-of-8,/maps/projects/caeg/data/production/LV7/009/02...,"2024-08-15, 17:42 CEST",0.0,264352557,6406,264343399,2752,264352557,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98770,LV7009027909,collapsed.refseq_vertebrate_other.8-of-8,/maps/projects/caeg/data/production/LV7/009/02...,"2024-08-15, 17:42 CEST",0.01,264352557,9576,264334766,8215,264352557,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [151]:
res

{"{'fastp__filtering_result', 'path_to_binf_multiqc_report', 'fastp__merged_and_filtered', 'fastp__read2_before_filtering', 'fastp__insert_size', 'library_id', 'fastp__command', 'fastp__summary', 'fastp__adapter_cutting', 'binf_multiqc_datetime', 'lane_read_trimtype_etc', 'fastp__polyx_trimming', 'fastp__read1_before_filtering'}": ['L001',
  'L002',
  'L003',
  'L004'],
 "{'fastqc_trimmed__Encoding', 'fastqc_trimmed__%GC', 'fastqc_raw__basic_statistics', 'library_id', 'fastqc_raw__sequence_duplication_levels', 'fastqc_trimmed__median_sequence_length', 'fastqc_raw__avg_sequence_length', 'fastqc_raw__Sequences flagged as poor quality', 'fastqc_raw__Encoding', 'fastqc_trimmed__Total Sequences', 'fastqc_raw__per_base_sequence_quality', 'fastqc_trimmed__per_base_sequence_quality', 'fastqc_trimmed__File type', 'fastqc_raw__Total Bases', 'fastqc_raw__median_sequence_length', 'fastqc_raw__overrepresented_sequences', 'fastqc_raw__per_base_sequence_content', 'binf_multiqc_datetime', 'fastqc_raw__sequence_length_distribution', 'fastqc_raw__per_sequence_quality_scores', 'fastqc_trimmed__per_base_sequence_content', 'fastqc_trimmed__Total Bases', 'fastqc_raw__adapter_content', 'fastqc_trimmed__per_sequence_quality_scores', 'fastqc_trimmed__per_tile_sequence_quality', 'path_to_binf_multiqc_report', 'fastqc_trimmed__per_base_n_content', 'fastqc_trimmed__adapter_content', 'fastqc_raw__Total Sequences', 'fastqc_trimmed__overrepresented_sequences', 'fastqc_raw__total_deduplicated_percentage', 'fastqc_raw__File type', 'lane_read_trimtype_etc', 'fastqc_trimmed__avg_sequence_length', 'fastqc_trimmed__sequence_length_distribution', 'fastqc_trimmed__per_sequence_gc_content', 'fastqc_trimmed__sequence_duplication_levels', 'fastqc_raw__per_base_n_content', 'fastqc_trimmed__total_deduplicated_percentage', 'fastqc_raw__per_tile_sequence_quality', 'fastqc_trimmed__Sequence length', 'fastqc_trimmed__Sequences flagged as poor quality', 'fastqc_trimmed__Filename', 'fastqc_raw__%GC', 'fastqc_raw__Sequence length', 'fastqc_raw__Filename', 'fastqc_trimmed__basic_statistics', 'fastqc_raw__per_sequence_gc_content'}": ['L001_R1',
  'L001_R2',
  'L002_R1',
  'L002_R2',
  'L003_R1',
  'L003_R2',
  'L004_R1',
  'L004_R2'],
 "{'fastqc_trimmed__Encoding', 'fastqc_trimmed__%GC', 'library_id', 'fastqc_trimmed__median_sequence_length', 'fastqc_trimmed__Total Sequences', 'fastqc_trimmed__per_base_sequence_quality', 'fastqc_trimmed__File type', 'binf_multiqc_datetime', 'fastqc_trimmed__per_base_sequence_content', 'fastqc_trimmed__Total Bases', 'fastqc_trimmed__per_sequence_quality_scores', 'fastqc_trimmed__per_tile_sequence_quality', 'path_to_binf_multiqc_report', 'fastqc_trimmed__adapter_content', 'fastqc_trimmed__overrepresented_sequences', 'lane_read_trimtype_etc', 'fastqc_trimmed__avg_sequence_length', 'fastqc_trimmed__sequence_length_distribution', 'fastqc_trimmed__per_sequence_gc_content', 'fastqc_trimmed__sequence_duplication_levels', 'fastqc_trimmed__total_deduplicated_percentage', 'fastqc_trimmed__Sequence length', 'fastqc_trimmed__Sequences flagged as poor quality', 'fastqc_trimmed__Filename', 'fastqc_trimmed__per_base_n_content', 'fastqc_trimmed__basic_statistics'}": ['L001_collapsed',
  'L001_singleton',
  'L002_collapsed',
  'L002_singleton',
  'L003_collapsed',
  'L003_singleton',
  'L004_collapsed',
  'L004_singleton'],
 "{'nonpareil_initial__nonpareil_version', 'nonpareil_derep__nonpareil_has.model', 'samtools_stats__bases_mapped_(cigar)', 'nonpareil_low_complexity__nonpareil_file', 'samtools_stats__reads_unmapped', 'nonpareil_derep__nonpareil_ksize', 'samtools_stats__total_first_fragment_length', 'samtools_stats__insert_size_standard_deviation', 'samtools_stats__reads_MQ0_percent', 'nonpareil_derep__nonpareil_x.adj', 'nonpareil_initial__nonpareil_star', 'nonpareil_initial__nonpareil_label', 'nonpareil_low_complexity__nonpareil_star', 'samtools_stats__reads_properly_paired_percent', 'nonpareil_derep__nonpareil_y.p50', 'samtools_stats__maximum_first_fragment_length', 'nonpareil_derep__nonpareil_y.p25', 'samtools_stats__filtered_sequences', 'nonpareil_low_complexity__nonpareil_x.obs', 'nonpareil_initial__nonpareil_warning', 'nonpareil_initial__nonpareil_y.sd', 'nonpareil_derep__nonpareil_y.cov', 'samtools_stats__reads_properly_paired', 'samtools_stats__percentage_of_properly_paired_reads_(%)', 'samtools_stats__reads_MQ0', 'samtools_stats__pairs_on_different_chromosomes', 'nonpareil_derep__nonpareil_log.sample', 'samtools_stats__reads_paired', 'nonpareil_derep__nonpareil_y.sd', 'nonpareil_initial__nonpareil_col', 'samtools_stats__is_sorted', 'nonpareil_initial__nonpareil_y.p50', 'nonpareil_initial__nonpareil_modelR', 'nonpareil_initial__nonpareil_x.model', 'nonpareil_low_complexity__nonpareil_AL', 'samtools_stats__reads_duplicated_percent', 'samtools_stats__raw_total_sequences', 'nonpareil_initial__nonpareil_R', 'nonpareil_derep__nonpareil_file', 'nonpareil_low_complexity__nonpareil_has.model', 'samtools_stats__reads_mapped_and_paired', 'samtools_stats__reads_mapped_percent', 'nonpareil_derep__nonpareil_model', 'nonpareil_derep__nonpareil_LRstar', 'nonpareil_initial__nonpareil_model', 'nonpareil_low_complexity__nonpareil_diversity', 'nonpareil_initial__nonpareil_kappa', 'nonpareil_initial__nonpareil_kernel', 'nonpareil_derep__nonpareil_R', 'nonpareil_low_complexity__nonpareil_LR', 'samtools_stats__supplementary_alignments', 'samtools_stats__pairs_with_other_orientation', 'nonpareil_derep__nonpareil_y.model', 'nonpareil_low_complexity__nonpareil_x.model', 'samtools_stats__bases_duplicated', 'samtools_stats__outward_oriented_pairs', 'nonpareil_low_complexity__nonpareil_L', 'samtools_stats__average_last_fragment_length', 'nonpareil_derep__nonpareil_overlap', 'nonpareil_low_complexity__nonpareil_y.red', 'samtools_stats__mismatches', 'nonpareil_derep__nonpareil_star', 'nonpareil_derep__nonpareil_consistent', 'nonpareil_initial__nonpareil_LRstar', 'nonpareil_low_complexity__nonpareil_version', 'samtools_stats__bases_mapped', 'nonpareil_low_complexity__nonpareil_label', 'nonpareil_derep__nonpareil_y.p75', 'nonpareil_low_complexity__nonpareil_y.p25', 'nonpareil_low_complexity__nonpareil_warning', 'nonpareil_derep__nonpareil_kappa', 'nonpareil_derep__nonpareil_warning', 'samtools_stats__total_last_fragment_length', 'samtools_stats__reads_mapped_and_paired_percent', 'nonpareil_initial__nonpareil_x.obs', 'nonpareil_derep__nonpareil_label', 'samtools_stats__error_rate', 'samtools_stats__reads_paired_percent', 'nonpareil_low_complexity__nonpareil_y.p75', 'nonpareil_initial__nonpareil_has.model', 'samtools_stats__insert_size_average', 'nonpareil_initial__nonpareil_LR', 'samtools_stats__average_first_fragment_length', 'nonpareil_initial__nonpareil_C', 'nonpareil_initial__nonpareil_y.model', 'nonpareil_derep__nonpareil_diversity', 'nonpareil_initial__nonpareil_x.adj', 'nonpareil_low_complexity__nonpareil_y.sd', 'samtools_stats__bases_trimmed', 'nonpareil_low_complexity__nonpareil_y.p50', 'samtools_stats__maximum_length', 'samtools_stats__total_length', 'nonpareil_low_complexity__nonpareil_model', 'nonpareil_low_complexity__nonpareil_consistent', 'path_to_binf_multiqc_report', 'nonpareil_derep__nonpareil_y.red', 'nonpareil_initial__nonpareil_overlap', 'lane_read_trimtype_etc', 'samtools_stats__non-primary_alignments', 'nonpareil_initial__nonpareil_y.p75', 'nonpareil_derep__nonpareil_col', 'samtools_stats__reads_QC_failed_percent', 'nonpareil_low_complexity__nonpareil_observed', 'nonpareil_initial__nonpareil_ksize', 'samtools_stats__average_length', 'samtools_stats__reads_duplicated', 'samtools_stats__reads_QC_failed', 'nonpareil_low_complexity__nonpareil_kernel', 'nonpareil_low_complexity__nonpareil_kappa', 'nonpareil_derep__nonpareil_x.model', 'nonpareil_initial__nonpareil_observed', 'samtools_stats__inward_oriented_pairs', 'samtools_stats__reads_unmapped_percent', 'nonpareil_derep__nonpareil_L', 'library_id', 'samtools_stats__reads_mapped', 'nonpareil_low_complexity__nonpareil_C', 'nonpareil_low_complexity__nonpareil_modelR', 'nonpareil_initial__nonpareil_y.red', 'nonpareil_low_complexity__nonpareil_LRstar', 'samtools_stats__sequences', 'nonpareil_derep__nonpareil_x.obs', 'nonpareil_derep__nonpareil_observed', 'nonpareil_low_complexity__nonpareil_log.sample', 'nonpareil_initial__nonpareil_AL', 'binf_multiqc_datetime', 'nonpareil_derep__nonpareil_modelR', 'nonpareil_derep__nonpareil_LR', 'nonpareil_low_complexity__nonpareil_y.model', 'nonpareil_derep__nonpareil_version', 'samtools_stats__maximum_last_fragment_length', 'nonpareil_initial__nonpareil_log.sample', 'nonpareil_initial__nonpareil_file', 'nonpareil_initial__nonpareil_y.cov', 'nonpareil_initial__nonpareil_diversity', 'samtools_stats__last_fragments', 'nonpareil_low_complexity__nonpareil_x.adj', 'nonpareil_low_complexity__nonpareil_overlap', 'samtools_stats__reads_mapped_MQ1', 'nonpareil_initial__nonpareil_L', 'nonpareil_low_complexity__nonpareil_R', 'samtools_stats__1st_fragments', 'nonpareil_derep__nonpareil_C', 'nonpareil_low_complexity__nonpareil_y.cov', 'nonpareil_low_complexity__nonpareil_col', 'nonpareil_derep__nonpareil_AL', 'nonpareil_low_complexity__nonpareil_ksize', 'nonpareil_derep__nonpareil_kernel', 'nonpareil_initial__nonpareil_y.p25', 'samtools_stats__average_quality', 'nonpareil_initial__nonpareil_consistent'}": ['collapsed'],
 "{'bowtie2__overall_alignment_rate', 'bowtie2__total_reads', 'bowtie2__unpaired_aligned_multi', 'path_to_binf_multiqc_report', 'bowtie2__unpaired_aligned_none', 'library_id', 'binf_multiqc_datetime', 'bowtie2__unpaired_total', 'lane_read_trimtype_etc', 'bowtie2__unpaired_aligned_one'}": ['collapsed.norway.1-of-7',
  'collapsed.norway.2-of-7',
  'collapsed.norway.3-of-7',
  'collapsed.norway.4-of-7',
  'collapsed.norway.5-of-7',
  'collapsed.norway.6-of-7',
  'collapsed.norway.7-of-7',
  'collapsed.nt.1-of-9',
  'collapsed.nt.2-of-9',
  'collapsed.nt.3-of-9',
  'collapsed.nt.4-of-9',
  'collapsed.nt.5-of-9',
  'collapsed.nt.6-of-9',
  'collapsed.nt.7-of-9',
  'collapsed.nt.8-of-9',
  'collapsed.nt.9-of-9',
  'collapsed.polar.1-of-1',
  'collapsed.polar_b3.1-of-1',
  'collapsed.polar_other.1-of-1',
  'collapsed.refseq_archaea_fungi_virus.1-of-1',
  'collapsed.refseq_invertebrate.1-of-3',
  'collapsed.refseq_invertebrate.2-of-3',
  'collapsed.refseq_invertebrate.3-of-3',
  'collapsed.refseq_mitochondrion.1-of-1',
  'collapsed.refseq_plant.1-of-5',
  'collapsed.refseq_plant.2-of-5',
  'collapsed.refseq_plant.3-of-5',
  'collapsed.refseq_plant.4-of-5',
  'collapsed.refseq_plant.5-of-5',
  'collapsed.refseq_plastid.1-of-1',
  'collapsed.refseq_protozoa.1-of-1',
  'collapsed.refseq_vertebrate_mammal.1-of-10',
  'collapsed.refseq_vertebrate_mammal.10-of-10',
  'collapsed.refseq_vertebrate_mammal.2-of-10',
  'collapsed.refseq_vertebrate_mammal.3-of-10',
  'collapsed.refseq_vertebrate_mammal.4-of-10',
  'collapsed.refseq_vertebrate_mammal.5-of-10',
  'collapsed.refseq_vertebrate_mammal.6-of-10',
  'collapsed.refseq_vertebrate_mammal.7-of-10',
  'collapsed.refseq_vertebrate_mammal.8-of-10',
  'collapsed.refseq_vertebrate_mammal.9-of-10',
  'collapsed.refseq_vertebrate_other.1-of-8',
  'collapsed.refseq_vertebrate_other.2-of-8',
  'collapsed.refseq_vertebrate_other.3-of-8',
  'collapsed.refseq_vertebrate_other.4-of-8',
  'collapsed.refseq_vertebrate_other.5-of-8',
  'collapsed.refseq_vertebrate_other.6-of-8',
  'collapsed.refseq_vertebrate_other.7-of-8',
  'collapsed.refseq_vertebrate_other.8-of-8',
  'collapsed.bact_archaea.1-of-1']}

In [136]:
str(set(mega_qc[mega_qc['lane_read_trimtype_etc']=='L001'].dropna(how='all', axis='columns').columns.sort_values()))

"{'fastp__filtering_result', 'path_to_binf_multiqc_report', 'fastp__merged_and_filtered', 'fastp__read2_before_filtering', 'fastp__insert_size', 'library_id', 'fastp__command', 'fastp__summary', 'fastp__adapter_cutting', 'binf_multiqc_datetime', 'lane_read_trimtype_etc', 'fastp__polyx_trimming', 'fastp__read1_before_filtering'}"

In [82]:
example_lib = 'LV7008865054'
len(giga_table[giga_table.library_id == example_lib][test_cols])

280

In [ ]:
len(mega_qc[mega_qc.library_id == example_lib][test_cols])

70

In [84]:
biggest_len = 0
biggest_lib = None
for lib_id in giga_table.library_id.unique():
    length = len(giga_table[giga_table['library_id'] == lib_id])
    if length > biggest_len:
        biggest_len = length
        biggest_lib = lib_id

In [85]:
biggest_lib

'LV7008961083'

In [86]:
biggest_len

1136

In [110]:
biggest_lib = giga_table[mega_meta.columns][giga_table['library_id'] == 'LV7008961083'].dropna(how='all', axis='columns')

NameError: name 'mega_qc' is not defined

In [111]:
biggest_lib.astype(str).apply(lambda x: len(x.unique()), axis='index').sort_values()

robot_sample_id                    1
idt_index_no                       1
i7_bases_in_adapter                1
i5_bases_in_adapter                1
indexing_pcr_date                  1
library_cleanup_date               1
library_qc_date                    1
dna_pooled                         1
expected_sequencing_data           1
submitting_date                    1
qpcr_date                          1
return_dna                         1
return_pool                        1
pool_to_seqc                       1
wet_lab_project_done_date          1
library_prep_method                1
prod_res_path                      1
seq_project_name                   1
barcode_sequence                   1
percent_pf_clusters                1
seq_clusters_raw_sum               1
return_library                     1
ct                                 1
pcr_cycle                          1
library_qc_result                  1
fastq_file_id                      1
wet_lab_customer_name              1
wet_lab_order_date                 1
wet_lab_order_id                   1
wet_lab_no                         1
wet_lab_total_sample_quantity      1
library_start_date                 1
edna_lysate_position               1
lysis_date                         1
edna_plate_id                      1
edna_plate_position                1
edna_lysate_plate_id               1
edna_concentration                 1
wet_lab_cleanup_date               1
library_plate_id                   1
library_plate_barcode              1
library_plate_position             1
library_leftover_volume            1
library_id                         1
library_concentration              1
library_peak_size                  1
edna_id                            1
seq_clusters_pf_sum                2
flowcell_id                        2
fastq_path                         2
seq_yield_mbases_sum               2
seqc_tube_tag                      2
fc_lane                            4
percent_of_the_flowcell_lane       4
percent_one_mismatch_barcode       8
seq_yield                          8
pf_clusters                        8
percent_greater_equal_q30_bases    8
mean_seq_quality_score             8
percent_perfect_barcode            8
dtype: int64