In [1]:
%env DB_PASSWORD = '5J8DhII0RRsPW1'

env: DB_PASSWORD='5J8DhII0RRsPW1'

In [2]:
import pandas as pd
import paramiko

from sqlalchemy import create_engine
ENGINE = create_engine(
    f"postgresql://postgres:Wtcantfw36c!@dandypdb01fl:5432/aedna_metadata_test")
import pandas as pd
meta = "select * from outer_coalesced_mega_table_meta"
meta = pd.read_sql(meta, ENGINE)

Theses IDs don't have a prod_res_path. Maybe because they were not uploaded to the sheet that generates the paths.

In [3]:
missing_paths = meta[(meta['country_ocean'].str.lower() == 'cambodia') & (meta['prod_res_path'].isna())][['library_id', 'prod_res_path']]['library_id'].dropna().unique()

In [4]:
len(meta[(meta['country_ocean'].str.lower() == 'cambodia')]['prod_res_path'].dropna().unique())

169

In [5]:
paths = meta[(meta['country_ocean'].str.lower() == 'cambodia') & (~meta['prod_res_path'].isna())][['library_id', 'prod_res_path']].drop_duplicates()

In [6]:
len(paths.library_id.unique())

169

In [7]:
hostname = 'dandyweb01fl'
port = 22
username = 'glj523'
password = 'Wtcantfw36c!123'

processed = {}

# Create an SSH client
client = paramiko.SSHClient()

# Automatically add the server's host key (if not already in known hosts)
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())

try:
    # Connect to the server
    client.connect(hostname, port=port, username=username, password=password)
    print(f"Connected to {hostname}")

    for i, row in paths.iterrows():
        path = row['prod_res_path']
        lib = row['library_id'] 
        # Execute a command
        stdin, stdout, stderr = client.exec_command(f'ls {path}')

        # Check for errors
        error = stderr.read().decode()
        if error:
            processed[lib] = error
        else:
            processed[lib] = stdout.read().decode()

finally:
    # Close the connection
    client.close()
    print("Connection closed.")

Connected to dandyweb01fl
Connection closed.

In [8]:
processed_df = pd.DataFrame(data=processed.items(), columns=['library_id', 'has_prod_results'])
processed_df['has_prod_results'] = processed_df['has_prod_results'].apply(lambda x: False if 'cannot access' in x else True)

In [9]:
processed_df.to_csv('cambodia.csv')

In [10]:
missing_paths

array(['Lib230329001', 'Lib230329012', 'Lib230329009', 'Lib230329011',
       'Lib230329007', 'Lib230329002', 'Lib230329013', 'Lib230329005',
       'Lib230329006', 'Lib230329008', 'Lib230329003', 'Lib230329004',
       'Lib230329010'], dtype=object)

In [11]:
hostname = 'dandyweb01fl'
port = 22
username = 'glj523'
password = 'Wtcantfw36c!123'

processed = {}

# Create an SSH client
client = paramiko.SSHClient()

# Automatically add the server's host key (if not already in known hosts)
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())

try:
    # Connect to the server
    client.connect(hostname, port=port, username=username, password=password)
    print(f"Connected to {hostname}")

    for path in missing_paths:

        # Execute a command
        stdin, stdout, stderr = client.exec_command(f'ls /projects/caeg/data/production/*/*/*/{path}/*')

        # Check for errors
        error = stderr.read().decode()
        if error:
            processed[path] = error
        else:
            processed[path] = stdout.read().decode()

finally:
    # Close the connection
    client.close()
    print("Connection closed.")

Connected to dandyweb01fl
Connection closed.

In [12]:
processed

{'Lib230329001': "ls: cannot access '/projects/caeg/data/production/*/*/*/Lib230329001/*': No such file or directory\n",
 'Lib230329012': "ls: cannot access '/projects/caeg/data/production/*/*/*/Lib230329012/*': No such file or directory\n",
 'Lib230329009': "ls: cannot access '/projects/caeg/data/production/*/*/*/Lib230329009/*': No such file or directory\n",
 'Lib230329011': "ls: cannot access '/projects/caeg/data/production/*/*/*/Lib230329011/*': No such file or directory\n",
 'Lib230329007': "ls: cannot access '/projects/caeg/data/production/*/*/*/Lib230329007/*': No such file or directory\n",
 'Lib230329002': "ls: cannot access '/projects/caeg/data/production/*/*/*/Lib230329002/*': No such file or directory\n",
 'Lib230329013': "ls: cannot access '/projects/caeg/data/production/*/*/*/Lib230329013/*': No such file or directory\n",
 'Lib230329005': "ls: cannot access '/projects/caeg/data/production/*/*/*/Lib230329005/*': No such file or directory\n",
 'Lib230329006': "ls: cannot access '/projects/caeg/data/production/*/*/*/Lib230329006/*': No such file or directory\n",
 'Lib230329008': "ls: cannot access '/projects/caeg/data/production/*/*/*/Lib230329008/*': No such file or directory\n",
 'Lib230329003': "ls: cannot access '/projects/caeg/data/production/*/*/*/Lib230329003/*': No such file or directory\n",
 'Lib230329004': "ls: cannot access '/projects/caeg/data/production/*/*/*/Lib230329004/*': No such file or directory\n",
 'Lib230329010': "ls: cannot access '/projects/caeg/data/production/*/*/*/Lib230329010/*': No such file or directory\n"}

In [13]:
missing_df = pd.DataFrame(data=processed.items(), columns=['library_id', 'has_prod_results'])
missing_df['has_prod_results'] = missing_df['has_prod_results'].apply(lambda x: False if 'cannot access' in x else True)

In [14]:
processed_df

       library_id  has_prod_results
0    LV3000765846              True
1    LV7001884436             False
2    LV7001884448             False
3    LV7001884449             False
4    LV7001884491             False
..            ...               ...
164  LV7009027812              True
165  LV7009027833              True
166  LV7009027860              True
167  LV7009027886              True
168  LV7009027909              True

[169 rows x 2 columns]

In [15]:
final = pd.concat([processed_df, missing_df])

In [16]:
final

      library_id  has_prod_results
0   LV3000765846              True
1   LV7001884436             False
2   LV7001884448             False
3   LV7001884449             False
4   LV7001884491             False
..           ...               ...
8   Lib230329006             False
9   Lib230329008             False
10  Lib230329003             False
11  Lib230329004             False
12  Lib230329010             False

[182 rows x 2 columns]

In [17]:
len(final)

182

In [18]:
bad = meta[meta['library_id'].isin(final[final['has_prod_results'] == False]['library_id'])]
good = meta[meta['library_id'].isin(final[final['has_prod_results'] == True]['library_id'])]

In [28]:
good['flowcell_id'].unique()

array([None, 'H5F5KDSX7', 'HNLW5DSX5'], dtype=object)

In [87]:
merged_uniq = {}

categorical_columns = bad.select_dtypes(include=["object", "category"]).columns
bad_unique_values = {
    col: list(bad[col].dropna().unique()) 
    for col in categorical_columns 
    if not bad[col].isna().all()
}

categorical_columns = good.select_dtypes(include=["object", "category"]).columns
good_unique_values = {
    col: list(good[col].dropna().unique()) 
    for col in categorical_columns 
    if not good[col].isna().all()
}

for col in categorical_columns:
    if col in bad_unique_values.keys() and col in good_unique_values.keys():
        merged_uniq[col] = (bad_unique_values[col], good_unique_values[col])

In [88]:
del merged_uniq['archive_sample_position_in_rack']
del merged_uniq['prod_res_path']
del merged_uniq['idt_index_no']
del merged_uniq['library_id']
del merged_uniq['library_plate_position']
del merged_uniq['library_plate_barcode']
del merged_uniq['library_plate_id']
del merged_uniq['edna_id']
del merged_uniq['edna_plate_position']
del merged_uniq['edna_lysate_position']
del merged_uniq['fastq_file_id']
del merged_uniq['robot_sample_position_in_rack']
del merged_uniq['robot_sample_rack_id']
del merged_uniq['robot_sample_rack_name']
del merged_uniq['archive_sample_ordered_depth_cal_tape']
del merged_uniq['archive_sample_rack_id']
del merged_uniq['archive_sample_rack_name']
del merged_uniq['fastq_path']
del merged_uniq['i5_bases_in_adapter']
del merged_uniq['i7_bases_in_adapter']
del merged_uniq['barcode_sequence']
del merged_uniq['archive_sample_id']
del merged_uniq['remarks_archive_sampling']
del merged_uniq['archive_sample_surface_exposed']
del merged_uniq['archive_sampling_by']
del merged_uniq['robot_sample_id']
del merged_uniq['robot_sample_sampled_by']
del merged_uniq['edna_lysate_plate_id']
del merged_uniq['edna_plate_id']
del merged_uniq['library_qc_result']
del merged_uniq['pcr_cycle']
del merged_uniq['expected_sequencing_data']
del merged_uniq['expected_sequencing_data']
del merged_uniq['expected_sequencing_data']
del merged_uniq['expected_sequencing_data']

KeyError: 'expected_sequencing_data'

In [89]:
for key in merged_uniq.keys():
    badval = merged_uniq[key][0]
    goodval = merged_uniq[key][1]
    if not str(badval) == str(goodval):
        print(key)
        print('Not processed: \t', sorted(badval))
        print('Processed: \t', sorted(goodval))
        print()

field_sample_id
Not processed: 	 ['CAM22-08', 'CAM2201']
Processed: 	 ['CAM22-08', 'CAM23-11', 'CAM23-13']

site_name
Not processed: 	 ['Angkor Thom Tempel Moat, Angkor', 'West Baray, Angkor']
Processed: 	 ['Angkor Thom Tempel Moat, Angkor', 'Northern Tempel Moat, Angkor Wat']

field_sampling_date
Not processed: 	 [datetime.date(2022, 4, 18), datetime.date(2022, 4, 20)]
Processed: 	 [datetime.date(2022, 4, 20), datetime.date(2023, 12, 7)]

field_sample_parent_id
Not processed: 	 ['CAM2201M', 'CAM2208M']
Processed: 	 ['CAM2208M', 'CAM2311M', 'CAM2313M']

field_sample_label
Not processed: 	 ['CAM2201_A', 'CAM2208']
Processed: 	 ['CAM2208', 'CAM2311', 'CAM2313']

archive_sample_submitter
Not processed: 	 ['NKL']
Processed: 	 ['KHK']

robot_sample_submitter
Not processed: 	 ['unknown']
Processed: 	 ['Unknown', 'skg401']

wet_lab_customer_name
Not processed: 	 ['Kurt Kjær']
Processed: 	 ['Kurt Kjær', 'Thorfinn Sand Korneliussen']

wet_lab_order_id
Not processed: 	 ['SS0036']
Processed: 	 ['SS0053', 'SS0090']

seqc_tube_tag
Not processed: 	 ['2ID2J']
Processed: 	 ['AOZCK', 'OBXCQ', 'PQFUO', 'WBDQ4']

submitting_date
Not processed: 	 ['05/04/2023']
Processed: 	 ['05/09/2023', '09-Jul-24', '28-Jun-24']

library_prep_method
Not processed: 	 ['double strand DNA Library Method']
Processed: 	 ['double strand DNA Library Method', 'single strand DNA Library Method']

seq_project_name
Not processed: 	 ['eDNALib046-A1-H6']
Processed: 	 ['eDNALib060-Thorfinn', 'ssDNALib0019']

flowcell_id
Not processed: 	 ['HMGMJDSX5']
Processed: 	 ['H5F5KDSX7', 'HNLW5DSX5']

In [93]:
bad['archive_sample_id'].unique()

array(['LV3005273250', 'LV3005273235', 'LV3005573878', 'LV3005273242',
       'LV3005273246', 'LV3005573865', 'LV3005573882', 'LV3005573872',
       'LV3005273227', 'LV3005573877', 'LV3005573870', 'LV3005573876',
       'LV3005273248'], dtype=object)