In [11]:
user = 'magnu'

In [12]:
import os
import pandas as pd
dir_path = fr"C:\Users\{user}\OneDrive - University of Copenhagen\Project Lanbarcode batch upload\lanebarcode"
file_names = os.listdir(dir_path)
lane_barcodes = pd.DataFrame(file_names)

special = fr"C:\Users\magnu\OneDrive - University of Copenhagen\Project Lanbarcode batch upload\Copy of list_all_SeqRuns_2024-2025_edit251113JBT.xlsx"
pool_tags = pd.read_excel(special, sheet_name='Sheet1')

In [13]:
lane_barcodes.rename(columns={0: 'filename'}, inplace=True)

In [14]:
for row in lane_barcodes.iterrows():
    split = row[1]['filename'].split('.')
    if split[1:] != ['lanebarcode', 'html']:
        raise ValueError(f"Unexpected file format: {row[1]['filename']}")
    else :

        lane_barcodes.at[row[0], 'run'] = split[0]

In [15]:
pattern = r'^(\d{8}|\d{6})_A00706_\d{4}_(A|B)[A-Z0-9]{9}(_.*\.lanebarcode\.html|\.lanebarcode\.html)$'
mask = lane_barcodes.filename.str.match(pattern)
assert mask.all(), "Some filenames do not match the expected pattern."

# Because we have confirmed the filename structure above we can confidently parse it here: 
lane_barcodes['date'] = lane_barcodes['filename'].apply(lambda x: x.split('_')[0])
lane_barcodes['machine'] = lane_barcodes['filename'].apply(lambda x: x.split('_')[1])
lane_barcodes['run_no'] = lane_barcodes['filename'].apply(lambda x: x.split('_')[2])
lane_barcodes['full_flowcell_id'] = lane_barcodes['filename'].apply(lambda x: x.split('_')[3][:10])
lane_barcodes['side'] = lane_barcodes['full_flowcell_id'].apply(lambda x: x[0])
lane_barcodes['flowcell_id'] = lane_barcodes['full_flowcell_id'].apply(lambda x: x[1:])

In [16]:
assert all(lane_barcodes['full_flowcell_id'].apply(len) == 10)
assert all(lane_barcodes['side'].apply(len) == 1)
assert all(lane_barcodes['flowcell_id'].apply(len) == 9)
assert all(lane_barcodes['run_no'].apply(len) == 4)
assert all(lane_barcodes['machine'].apply(len) == 6)

Check whats already uploaded

In [17]:
lane_barcodes

,filename,run,date,machine,run_no,full_flowcell_id,side,flowcell_id
0,20241106_A00706_0891_AHK27KDRX5.lanebarcode.html,20241106_A00706_0891_AHK27KDRX5,20241106,A00706,0891,AHK27KDRX5,A,HK27KDRX5
1,20241106_A00706_0892_BH5CTKDSX7.lanebarcode.html,20241106_A00706_0892_BH5CTKDSX7,20241106,A00706,0892,BH5CTKDSX7,B,H5CTKDSX7
2,20241108_A00706_0893_AH5CVTDSX7.lanebarcode.html,20241108_A00706_0893_AH5CVTDSX7,20241108,A00706,0893,AH5CVTDSX7,A,H5CVTDSX7
3,20241129_A00706_0894_BH5FLYDSX7.lanebarcode.html,20241129_A00706_0894_BH5FLYDSX7,20241129,A00706,0894,BH5FLYDSX7,B,H5FLYDSX7
4,20241129_A00706_0895_AHKVJGDRX5.lanebarcode.html,20241129_A00706_0895_AHKVJGDRX5,20241129,A00706,0895,AHKVJGDRX5,A,HKVJGDRX5
...,...,...,...,...,...,...,...,...
216,240926_A00706_0885_AH5FHKDSX7_TTS56_ITXBC.lane...,240926_A00706_0885_AH5FHKDSX7_TTS56_ITXBC,240926,A00706,0885,AH5FHKDSX7,A,H5FHKDSX7
217,241008_A00706_0886_AHMGK3DSXC_FASTQ.lanebarcod...,241008_A00706_0886_AHMGK3DSXC_FASTQ,241008,A00706,0886,AHMGK3DSXC,A,HMGK3DSXC
218,241011_A00706_0887_AHMFH5DSXC_HL8MP.lanebarcod...,241011_A00706_0887_AHMFH5DSXC_HL8MP,241011,A00706,0887,AHMFH5DSXC,A,HMFH5DSXC
219,241015_A00706_0889_AHVJTCDSXC_YLP56.lanebarcod...,241015_A00706_0889_AHVJTCDSXC_YLP56,241015,A00706,0889,AHVJTCDSXC,A,HVJTCDSXC
220,241022_A00706_0890_AHJMM2DRX5_CXFTJ_CXHVL.lane...,241022_A00706_0890_AHJMM2DRX5_CXFTJ_CXHVL,241022,A00706,0890,AHJMM2DRX5,A,HJMM2DRX5

In [18]:
pool_tags

,ID,BSSHRunID,WorkingID,Tubetag,RunSheetID,RunDate,InstrumentID,FlowCellID,InstrumentSide,SequencingOK,Notes by Julie
0,425,251010_A00706_0985_BHHTTFDSXF,250917_L2FUG_Kurt,L2FUG,251010_S4FCB,2025-10-10,A00706,HHTTFDSXF,B,True,NaN
1,420,251006_A00706_0980_BHHNHVDSXF,250905_PCOZJ_Mikkel,PCOZJ,251006_S4FCB,2025-10-06,A00706,HHNHVDSXF,B,True,NaN
2,417,250926_A00706_0976_BHHLMCDSXF,250826_HBUAO_Mikkel,HBUAO,250926_S4FCB,2025-09-26,A00706,HHLMCDSXF,B,True,NaN
3,415,250909_A00706_0973_BHCMC3DSXF,250811_LTKYS_Yucheng,LTKYS,250909_S4FCB,2025-09-09,A00706,HCMC3DSXF,B,True,NaN
4,413,250905_A00706_0972_BHK3VCDSXF,250808_MQDQP_Mikkel,MQDQP,250905_S4FCB,2025-09-05,A00706,HK3VCDSXF,B,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...
106,156,240202_A00706_0816_AHTNTGDSX5,240124_SYBP6_Zaruhi,SYBP6,240202_S4FCA,2024-02-02,A00706,HTNTGDSX5,A,True,"This is not an XP-run, even though there's two..."
107,56,240129_A00706_0812_AHTMWGDSX5,240122_QXT5U_Zaruhi,QXT5U,240129_S4FCA,2024-01-29,A00706,HTMWGDSX5,A,True,NaN
108,37,240126_A00706_0811_AHTMW2DSX5,240118_ZTM3M_Maria,ZTM3M,240126_S4FCA,2024-01-26,A00706,HTMW2DSX5,A,True,NaN
109,36,240117_A00706_0808_AHTMGNDSX5,231204_BNW8A_Zaruhi,BNW8A,240117_S4FCA,2024-01-17,A00706,HTMGNDSX5,A,True,NaN
110,59,240131_A00706_0814_AHTT2WDSX5,240124_OYHVD_Zaruhi,OYHVD,240131_S4FCA,2024-01-31,A00706,HTT2WDSX5,A,True,NaN

In [19]:
from pathlib import Path
import sys
import os

def find_project_root():
    path = Path(os.getcwd()).resolve()
    while path != path.root:
        if (path / 'very_rootsy_file.txt').exists():
            return path
        path = path.parent
    return None  # Project root not found

project_root = find_project_root()

sys.path.append(str(project_root))

In [20]:
%env PGPASSWORD=5J8DhII0RRsPW1

env: PGPASSWORD=5J8DhII0RRsPW1

In [26]:
from constants.db_connections import ENGINE, ENGINE_READ_ONLY, SQL_ALCH_CONFIG, PSY_CONN
q = 'select * from flowcell'
flowcell_db = pd.read_sql(q, ENGINE_READ_ONLY)
flowcell_db['full_flowcell_id'] = flowcell_db['flowcell_position'] + flowcell_db['flowcell_id']

q = 'select * from top_unknown_seq_barcodes'
tusb_db = pd.read_sql(q, ENGINE_READ_ONLY)

In [27]:
mask = lane_barcodes['flowcell_id'].isin(flowcell_db['flowcell_id'])
lane_barcodes_in_db = lane_barcodes[mask].copy()
lane_barcodes_not_in_db = lane_barcodes[~mask].copy()

mask = pool_tags['FlowCellID'].isin(flowcell_db['flowcell_id'])
pool_tags_in_db = pool_tags[mask].copy()    
pool_tags_not_in_db = pool_tags[~mask].copy()

In [36]:
pool_tags_not_in_db.to_excel(r'C:\Users\magnu\OneDrive - University of Copenhagen\Project Lanbarcode batch upload\pool_tags_not_in_db.xlsx', index=False)

In [37]:
lane_barcodes_not_in_db.to_excel(r'C:\Users\magnu\OneDrive - University of Copenhagen\Project Lanbarcode batch upload\lane_barcodes_not_in_db.xlsx', index=False)

In [32]:
pool_tags_not_in_db['FlowCellID'].isin(lane_barcodes_not_in_db['flowcell_id']).value_counts()

FlowCellID
False    32
Name: count, dtype: int64

In [33]:
lane_barcodes_not_in_db['flowcell_id'].isin(pool_tags_not_in_db['FlowCellID']).value_counts()

flowcell_id
False    118
Name: count, dtype: int64

In [13]:
lane_barcodes

,filename,run,date,machine,run_no,full_flowcell_id,side,flowcell_id
152,240202_A00706_0816_AHTNTGDSX5.lanebarcode.html,240202_A00706_0816_AHTNTGDSX5,240202,A00706,0816,AHTNTGDSX5,A,HTNTGDSX5
153,240202_A00706_0817_BHTT3LDSX5.lanebarcode.html,240202_A00706_0817_BHTT3LDSX5,240202,A00706,0817,BHTT3LDSX5,B,HTT3LDSX5
212,240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lane...,240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X,240916,A00706,0879,AHHVLVDSXC,A,HHVLVDSXC

In [14]:
lane_barcodes

,filename,run,date,machine,run_no,full_flowcell_id,side,flowcell_id
152,240202_A00706_0816_AHTNTGDSX5.lanebarcode.html,240202_A00706_0816_AHTNTGDSX5,240202,A00706,0816,AHTNTGDSX5,A,HTNTGDSX5
153,240202_A00706_0817_BHTT3LDSX5.lanebarcode.html,240202_A00706_0817_BHTT3LDSX5,240202,A00706,0817,BHTT3LDSX5,B,HTT3LDSX5
212,240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lane...,240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X,240916,A00706,0879,AHHVLVDSXC,A,HHVLVDSXC

In [15]:
# Filter out any flowcell IDs already in the database
mask = pool_tags['FlowCellID'].isin(flowcell_db.flowcell_id)
print(mask.value_counts())
pool_tags = pool_tags[~mask]
mask = lane_barcodes['flowcell_id'].isin(flowcell_db.flowcell_id)
print(mask.value_counts())
lane_barcodes = lane_barcodes[~mask]

FlowCellID
True     4
False    2
Name: count, dtype: int64
flowcell_id
True     2
False    1
Name: count, dtype: int64

In [16]:
pool_tags

,ID,BSSHRunID,WorkingID,Tubetag,RunSheetID,RunDate,InstrumentID,FlowCellID,InstrumentSide,SequencingOK,Notes by Julie
4,195,240916_A00706_0879_AHHVLVDSXC,240821_I5R2U_Xihan,I5R2U,240916_S4FCA,2024-09-16,A00706,HHVLVDSXC,A,True,"This is not an XP-run, even though there's two..."
5,196,240916_A00706_0879_AHHVLVDSXC,240821_J5U5X_Xihan,J5U5X,240916_S4FCA,2024-09-16,A00706,HHVLVDSXC,A,True,"This is not an XP-run, even though there's two..."

In [17]:
lane_barcodes

,filename,run,date,machine,run_no,full_flowcell_id,side,flowcell_id
212,240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lane...,240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X,240916,A00706,0879,AHHVLVDSXC,A,HHVLVDSXC

Get all flowcell data to upload into one df

In [18]:
from constants.db_names.names import data
import lane_barcode_parser

fc = []
tpb = []

for file_name in lane_barcodes.filename:
    file_path = os.path.join(dir_path, file_name)

    tube_tag_col_name = data.flowcell.library_pool_tag()
    read_len_col_name = data.flowcell.read_length()
    seq_machine_col_name = data.flowcell.sequencing_machine()
    seq_date_col_name = data.flowcell.sequencing_date()
    flowcell_pos_col_name = data.flowcell.flowcell_position()
    seq_run_col_name = data.flowcell.sequencing_run()
    print(file_name)
    print(file_path)
    sheet = pd.read_html(file_path, thousands=',', decimal='.')

    flowcell_data, top_unknown_barcodes = lane_barcode_parser.parse(df=sheet)
    flowcell_data['upload_sheet'] = str(file_name)
    top_unknown_barcodes['upload_sheet'] = str(file_name)

    fc.append(flowcell_data)
    tpb.append(top_unknown_barcodes)

240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lanebarcode.html
C:\Users\magnu\OneDrive - University of Copenhagen\Project Lanbarcode batch upload\lanebarcode\240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lanebarcode.html

In [19]:
top_unknown_barcodes = pd.concat(tpb, ignore_index=True)
flowcell_data = pd.concat(fc, ignore_index=True)

In [20]:
pool_tags.rename(columns={'FlowCellID': 'Flowcell ID'}, inplace=True)

In [21]:
mask = special_data.duplicated('Unique Sample ID', keep=False)
special_data[mask]

,LibraryID,Unique Sample ID,P7_INDEX_ID,P7_INDEX_Seq,P5_INDEX_ID,P5_INDEX_Seq
0,MYUGL,LV7008958707-ExrNTC23102901-ExrNTC,UDP144,AATCCAATTG,UDP144,CCTCTACATG
21,MYUGL,LV7008957350-LibNTC23112804-LibNTC,UDP192,CCGGTAACAC,UDP192,AGTACAACTC
68,SYBP6,LV7008958707-ExrNTC23102901-ExrNTC,UDP144,AATCCAATTG,UDP144,CCTCTACATG
95,SYBP6,LV7008957350-LibNTC23112804-LibNTC,UDP192,CCGGTAACAC,UDP192,AGTACAACTC

In [22]:
merge = flowcell_data.merge(special_data[['LibraryID', 'Unique Sample ID']], left_on='Sample', right_on='Unique Sample ID', how='inner', validate='many_to_many')

In [23]:
merge.drop(columns=['Unique Sample ID'], inplace=True)

In [24]:
flowcell_data = merge

Get read length, sequencing date, tubetag, seq machine, seq run and flowcell pos merged in

In [25]:
machine_id_map = {
                'A00706': {
                    'name': 'Nova Seq 6000',
                    'rl': '101'
                }
            }
top_unknown_barcodes.loc[:, 'read_length'] = machine_id_map['A00706']['rl']
top_unknown_barcodes.loc[:, 'sequencing_machine'] = machine_id_map['A00706']['name']
flowcell_data.loc[:, 'read_length'] = machine_id_map['A00706']['rl']
flowcell_data.loc[:, 'sequencing_machine'] = machine_id_map['A00706']['name']

In [26]:
q = 'select column_name_db, column_name_sheet from name_maps.column_names where table_id = 9'
flowcell_name_maps = pd.read_sql(q, ENGINE_READ_ONLY)
flowcell_name_maps = flowcell_name_maps.dropna()
flowcell_name_maps.index = flowcell_name_maps['column_name_sheet']
flowcell_name_maps.drop(columns=['column_name_sheet'], inplace=True)

In [27]:
q = 'select column_name_db, column_name_sheet from name_maps.column_names where table_id = 18'
tusb_name_maps = pd.read_sql(q, ENGINE_READ_ONLY)
tusb_name_maps = tusb_name_maps.dropna()
tusb_name_maps.index = tusb_name_maps['column_name_sheet']
tusb_name_maps.drop(columns=['column_name_sheet'], inplace=True)

In [28]:
translator_tusb = tusb_name_maps.to_dict(orient='dict')['column_name_db']
translator_fc = flowcell_name_maps.to_dict(orient='dict')['column_name_db']

In [29]:
flowcell_data = flowcell_data.rename(columns=translator_fc)
top_unknown_barcodes = top_unknown_barcodes.rename(columns=translator_tusb)

In [31]:
fc_to_upload = flowcell_data   
tusb_to_upload = top_unknown_barcodes

tusb_to_upload['database_insert_by'] = 'julie.bitz-thorsen@sund.ku.dk'
fc_to_upload['database_insert_by'] = 'julie.bitz-thorsen@sund.ku.dk'
from datetime import datetime, timezone

ts = datetime.now(timezone.utc)  
tusb_to_upload['database_insert_datetime_utc'] = ts
fc_to_upload['database_insert_datetime_utc'] = ts
from uuid import uuid4
tusb_to_upload['upload_uuid'] = uuid4()
tusb_to_upload = tusb_to_upload.replace(["nan", "NaN", "NAN", "null", "NULL", "None", "none"], None)
fc_to_upload['upload_uuid'] = uuid4()
fc_to_upload = fc_to_upload.replace(["nan", "NaN", "NAN", "null", "NULL", "None", "none"], None)

In [32]:
tusb_to_upload.drop(columns=['ID', 
                             'BSSHRunID',
                             'WorkingID',
                             'RunSheetID',
                             'InstrumentID',
                             'Notes by Julie',
                             'SequencingOK',
                             'full_flowcell_id',
                             'duplicate_flowcell',
                             'run',
                             'date',
                             'machine',
                             'side',
                             'flowcell', 
                             'ttags'],
                             inplace=True, errors='ignore')
fc_to_upload.drop(columns=['ID', 
                             'BSSHRunID',
                             'WorkingID',
                             'RunSheetID',
                             'InstrumentID',
                             'Notes by Julie',
                             'SequencingOK',
                             'full_flowcell_id',
                             'duplicate_flowcell',
                             'run',
                             'date',
                             'machine',
                             'side',
                             'flowcell', 
                             'ttags'],
                             inplace=True, errors='ignore')

In [33]:
tusb_to_upload = tusb_to_upload.rename(columns=translator_tusb)
fc_to_upload = fc_to_upload.rename(columns=translator_fc)

In [34]:
renamer = {
    'RunDate': 'sequencing_date',
    'LibraryID': 'seqc_tube_tag',
    'InstrumentSide': 'flowcell_position'
}

fc_to_upload.rename(columns=renamer, inplace=True)

In [35]:
red_cols = set(tusb_to_upload.columns) - set(tusb_db.columns)
print(red_cols)
tusb_to_upload.drop(columns=red_cols, inplace=True)
red_cols = set(fc_to_upload.columns) - set(flowcell_db.columns)
print(red_cols)
fc_to_upload.drop(columns=red_cols, inplace=True)

set()
set()

In [36]:
fc_to_upload

,flowcell_lane,wet_lab_project_name,fastq_file_id,dna_barcode_sequence,pf_clusters,percent_of_the_flow_cell_lane,percent_perfect_dna_barcode,percent_one_mismatch_dna_barcode,flowcell_yield_mbases,percent_pf_clusters,...,flowcell_clusters_raw_sum,flowcell_clusters_pf_sum,flowcell_yield_mbases_sum,upload_sheet,seqc_tube_tag,read_length,sequencing_machine,database_insert_by,database_insert_datetime_utc,upload_uuid
0,1,PlantTissue,LV7008953919-LV7005366640-CGG1025505,TATGATGGCC+TATGACAATC,77543073,2.91,93.8,6.2,15664,100.0,...,15320088576,10540832034,2129248,240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lane...,J5U5X,101,Nova Seq 6000,julie.bitz-thorsen@sund.ku.dk,2025-12-22 16:32:07.129710+00:00,2d9ed74e-0000-4baf-b92c-51c6bd34ec62
1,1,PlantTissue,LV7008956496-LV7005366620-CGG1025524,AATTCCATCT+GTAACTGAAG,16609289,0.62,95.33,4.67,3355,100.0,...,15320088576,10540832034,2129248,240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lane...,J5U5X,101,Nova Seq 6000,julie.bitz-thorsen@sund.ku.dk,2025-12-22 16:32:07.129710+00:00,2d9ed74e-0000-4baf-b92c-51c6bd34ec62
2,1,PlantTissue,LV7008956497-LV7005366603-CGG1025512,CCACGCTGAA+CTGAGGAATA,40613058,1.52,96.03,3.97,8204,100.0,...,15320088576,10540832034,2129248,240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lane...,J5U5X,101,Nova Seq 6000,julie.bitz-thorsen@sund.ku.dk,2025-12-22 16:32:07.129710+00:00,2d9ed74e-0000-4baf-b92c-51c6bd34ec62
3,1,PlantTissue,LV7008956508-LV7005366628-CGG1025525,TTAACGGTGT+ACGGTCAGGA,47458676,1.78,94.0,6.0,9587,100.0,...,15320088576,10540832034,2129248,240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lane...,J5U5X,101,Nova Seq 6000,julie.bitz-thorsen@sund.ku.dk,2025-12-22 16:32:07.129710+00:00,2d9ed74e-0000-4baf-b92c-51c6bd34ec62
4,1,PlantTissue,LV7008956509-LV7005364009-CGG1025513,GTTCGGAGTT+TCAGAAGGCG,39502799,1.48,97.02,2.98,7980,100.0,...,15320088576,10540832034,2129248,240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lane...,J5U5X,101,Nova Seq 6000,julie.bitz-thorsen@sund.ku.dk,2025-12-22 16:32:07.129710+00:00,2d9ed74e-0000-4baf-b92c-51c6bd34ec62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,4,Quids,LV7008886588-LV6000200947-024948A-s2,TGCCGGTCAG+TTGTATCAGG,22562314,0.88,94.15,5.85,4558,100.0,...,15320088576,10540832034,2129248,240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lane...,I5R2U,101,Nova Seq 6000,julie.bitz-thorsen@sund.ku.dk,2025-12-22 16:32:07.129710+00:00,2d9ed74e-0000-4baf-b92c-51c6bd34ec62
256,4,Quids,LV7008886589-LV6000200986-024952B-s1,CAGCAATCGT+ATACATCACA,47487220,1.85,94.98,5.02,9592,100.0,...,15320088576,10540832034,2129248,240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lane...,I5R2U,101,Nova Seq 6000,julie.bitz-thorsen@sund.ku.dk,2025-12-22 16:32:07.129710+00:00,2d9ed74e-0000-4baf-b92c-51c6bd34ec62
257,4,Quids,LV7008886590-LV6000201003-024954C-s1,GAATTACAAG+CTGAGCCGGT,45834931,1.79,95.31,4.69,9259,100.0,...,15320088576,10540832034,2129248,240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lane...,I5R2U,101,Nova Seq 6000,julie.bitz-thorsen@sund.ku.dk,2025-12-22 16:32:07.129710+00:00,2d9ed74e-0000-4baf-b92c-51c6bd34ec62
258,4,Quids,LV7008886592-LV6000200973-024956C-s1,AGAGAACCTA+TAGCATAACC,10005098,0.39,93.22,6.78,2021,100.0,...,15320088576,10540832034,2129248,240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lane...,I5R2U,101,Nova Seq 6000,julie.bitz-thorsen@sund.ku.dk,2025-12-22 16:32:07.129710+00:00,2d9ed74e-0000-4baf-b92c-51c6bd34ec62
259,4,Quids,LV7008957220-LV7005225801-24956-3,TCTAGGCGCG+TTAACCTTCG,366325405,14.31,96.18,3.82,73998,100.0,...,15320088576,10540832034,2129248,240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lane...,I5R2U,101,Nova Seq 6000,julie.bitz-thorsen@sund.ku.dk,2025-12-22 16:32:07.129710+00:00,2d9ed74e-0000-4baf-b92c-51c6bd34ec62

In [37]:
fc_to_upload.to_sql('flowcell', ENGINE, if_exists='append', index=False)

260

In [38]:
tusb_to_upload.to_sql('top_unknown_seq_barcodes', ENGINE, if_exists='append', index=False)

IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "top_unknown_seq_barcodes_pkey"
DETAIL:  Key (unknown_barcode_lane, unknown_barcode_sequence, flowcell_id)=(1, TCTAGGCGCG+GGGGGGGGGG, HHVLVDSXC) already exists.

[SQL: INSERT INTO top_unknown_seq_barcodes (unknown_barcode_lane, unknown_barcode_count, unknown_barcode_sequence, flowcell_id, upload_sheet, read_length, sequencing_machine, database_insert_by, database_insert_datetime_utc, upload_uuid) VALUES (%(unknown_ ... 10827 characters truncated ... achine__39)s, %(database_insert_by__39)s, %(database_insert_datetime_utc__39)s, %(upload_uuid__39)s)]
[parameters: {'database_insert_by__0': 'julie.bitz-thorsen@sund.ku.dk', 'database_insert_datetime_utc__0': datetime.datetime(2025, 12, 22, 16, 32, 7, 129710, tzinfo=datetime.timezone.utc), 'unknown_barcode_count__0': '1911040', 'upload_sheet__0': '240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lanebarcode.html', 'sequencing_machine__0': 'Nova Seq 6000', 'upload_uuid__0': UUID('a53579d9-c90f-4c5c-aa60-9b6be492afae'), 'flowcell_id__0': 'HHVLVDSXC', 'read_length__0': '101', 'unknown_barcode_sequence__0': 'TCTAGGCGCG+GGGGGGGGGG', 'unknown_barcode_lane__0': '1', 'database_insert_by__1': 'julie.bitz-thorsen@sund.ku.dk', 'database_insert_datetime_utc__1': datetime.datetime(2025, 12, 22, 16, 32, 7, 129710, tzinfo=datetime.timezone.utc), 'unknown_barcode_count__1': '1062880', 'upload_sheet__1': '240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lanebarcode.html', 'sequencing_machine__1': 'Nova Seq 6000', 'upload_uuid__1': UUID('a53579d9-c90f-4c5c-aa60-9b6be492afae'), 'flowcell_id__1': 'HHVLVDSXC', 'read_length__1': '101', 'unknown_barcode_sequence__1': 'GGGGGGGGGG+TTAACCTTCG', 'unknown_barcode_lane__1': '1', 'database_insert_by__2': 'julie.bitz-thorsen@sund.ku.dk', 'database_insert_datetime_utc__2': datetime.datetime(2025, 12, 22, 16, 32, 7, 129710, tzinfo=datetime.timezone.utc), 'unknown_barcode_count__2': '816540', 'upload_sheet__2': '240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lanebarcode.html', 'sequencing_machine__2': 'Nova Seq 6000', 'upload_uuid__2': UUID('a53579d9-c90f-4c5c-aa60-9b6be492afae'), 'flowcell_id__2': 'HHVLVDSXC', 'read_length__2': '101', 'unknown_barcode_sequence__2': 'GCGCGGCGCG+GGCCCCGGCG', 'unknown_barcode_lane__2': '1', 'database_insert_by__3': 'julie.bitz-thorsen@sund.ku.dk', 'database_insert_datetime_utc__3': datetime.datetime(2025, 12, 22, 16, 32, 7, 129710, tzinfo=datetime.timezone.utc), 'unknown_barcode_count__3': '787420', 'upload_sheet__3': '240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lanebarcode.html', 'sequencing_machine__3': 'Nova Seq 6000', 'upload_uuid__3': UUID('a53579d9-c90f-4c5c-aa60-9b6be492afae'), 'flowcell_id__3': 'HHVLVDSXC', 'read_length__3': '101', 'unknown_barcode_sequence__3': 'AAATATGAAC+TATGACAATC', 'unknown_barcode_lane__3': '1', 'database_insert_by__4': 'julie.bitz-thorsen@sund.ku.dk', 'database_insert_datetime_utc__4': datetime.datetime(2025, 12, 22, 16, 32, 7, 129710, tzinfo=datetime.timezone.utc), 'unknown_barcode_count__4': '734960', 'upload_sheet__4': '240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lanebarcode.html', 'sequencing_machine__4': 'Nova Seq 6000', 'upload_uuid__4': UUID('a53579d9-c90f-4c5c-aa60-9b6be492afae'), 'flowcell_id__4': 'HHVLVDSXC', 'read_length__4': '101', 'unknown_barcode_sequence__4': 'TTCGGTGTGA+ACCGTGTGGT', 'unknown_barcode_lane__4': '1' ... 300 parameters truncated ... 'database_insert_by__35': 'julie.bitz-thorsen@sund.ku.dk', 'database_insert_datetime_utc__35': datetime.datetime(2025, 12, 22, 16, 32, 7, 129710, tzinfo=datetime.timezone.utc), 'unknown_barcode_count__35': '628900', 'upload_sheet__35': '240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lanebarcode.html', 'sequencing_machine__35': 'Nova Seq 6000', 'upload_uuid__35': UUID('a53579d9-c90f-4c5c-aa60-9b6be492afae'), 'flowcell_id__35': 'HHVLVDSXC', 'read_length__35': '101', 'unknown_barcode_sequence__35': 'CTTATTGGCC+GGGGGGGGGG', 'unknown_barcode_lane__35': '4', 'database_insert_by__36': 'julie.bitz-thorsen@sund.ku.dk', 'database_insert_datetime_utc__36': datetime.datetime(2025, 12, 22, 16, 32, 7, 129710, tzinfo=datetime.timezone.utc), 'unknown_barcode_count__36': '619640', 'upload_sheet__36': '240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lanebarcode.html', 'sequencing_machine__36': 'Nova Seq 6000', 'upload_uuid__36': UUID('a53579d9-c90f-4c5c-aa60-9b6be492afae'), 'flowcell_id__36': 'HHVLVDSXC', 'read_length__36': '101', 'unknown_barcode_sequence__36': 'AGTACTCATG+ACAACAACAT', 'unknown_barcode_lane__36': '4', 'database_insert_by__37': 'julie.bitz-thorsen@sund.ku.dk', 'database_insert_datetime_utc__37': datetime.datetime(2025, 12, 22, 16, 32, 7, 129710, tzinfo=datetime.timezone.utc), 'unknown_barcode_count__37': '618740', 'upload_sheet__37': '240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lanebarcode.html', 'sequencing_machine__37': 'Nova Seq 6000', 'upload_uuid__37': UUID('a53579d9-c90f-4c5c-aa60-9b6be492afae'), 'flowcell_id__37': 'HHVLVDSXC', 'read_length__37': '101', 'unknown_barcode_sequence__37': 'ATAAATGAAC+ACTTGTTATC', 'unknown_barcode_lane__37': '4', 'database_insert_by__38': 'julie.bitz-thorsen@sund.ku.dk', 'database_insert_datetime_utc__38': datetime.datetime(2025, 12, 22, 16, 32, 7, 129710, tzinfo=datetime.timezone.utc), 'unknown_barcode_count__38': '614700', 'upload_sheet__38': '240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lanebarcode.html', 'sequencing_machine__38': 'Nova Seq 6000', 'upload_uuid__38': UUID('a53579d9-c90f-4c5c-aa60-9b6be492afae'), 'flowcell_id__38': 'HHVLVDSXC', 'read_length__38': '101', 'unknown_barcode_sequence__38': 'TAATTAGCGT+TCGGCGGTTA', 'unknown_barcode_lane__38': '4', 'database_insert_by__39': 'julie.bitz-thorsen@sund.ku.dk', 'database_insert_datetime_utc__39': datetime.datetime(2025, 12, 22, 16, 32, 7, 129710, tzinfo=datetime.timezone.utc), 'unknown_barcode_count__39': '607760', 'upload_sheet__39': '240916_A00706_0879_AHHVLVDSXC_I5R2U_J5U5X.lanebarcode.html', 'sequencing_machine__39': 'Nova Seq 6000', 'upload_uuid__39': UUID('a53579d9-c90f-4c5c-aa60-9b6be492afae'), 'flowcell_id__39': 'HHVLVDSXC', 'read_length__39': '101', 'unknown_barcode_sequence__39': 'AGAACCAAAT+ATAGCGGAAT', 'unknown_barcode_lane__39': '4'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [ ]:
tusb_to_upload

,unknown_barcode_count,unknown_barcode_sequence,upload_sheet,unknown_barcode_lane,flowcell_id,read_length,sequencing_machine,database_insert_by,database_insert_datetime_utc,upload_uuid
0,6834280,AGGCCGTGGA+CCCGCACGAG,240227_A00706_0832_BH3CGFDSX7.lanebarcode.html,1,H3CGFDSX7,101,Nova Seq 6000,julie.bitz-thorsen@sund.ku.dk,2025-12-22 15:27:51.869135+00:00,b8c635d1-df46-4e78-9efe-f10dbb35eccb
1,6036860,ATCGGCGAAG+CCTTCTTGGA,240227_A00706_0832_BH3CGFDSX7.lanebarcode.html,1,H3CGFDSX7,101,Nova Seq 6000,julie.bitz-thorsen@sund.ku.dk,2025-12-22 15:27:51.869135+00:00,b8c635d1-df46-4e78-9efe-f10dbb35eccb
2,5852940,GCAATATTCA+CCTTGGCGCC,240227_A00706_0832_BH3CGFDSX7.lanebarcode.html,1,H3CGFDSX7,101,Nova Seq 6000,julie.bitz-thorsen@sund.ku.dk,2025-12-22 15:27:51.869135+00:00,b8c635d1-df46-4e78-9efe-f10dbb35eccb
3,3874760,GGCCAATATT+GCTCGGACCG,240227_A00706_0832_BH3CGFDSX7.lanebarcode.html,1,H3CGFDSX7,101,Nova Seq 6000,julie.bitz-thorsen@sund.ku.dk,2025-12-22 15:27:51.869135+00:00,b8c635d1-df46-4e78-9efe-f10dbb35eccb
4,3119840,CGTGTACCAG+CCCTTATCCT,240227_A00706_0832_BH3CGFDSX7.lanebarcode.html,1,H3CGFDSX7,101,Nova Seq 6000,julie.bitz-thorsen@sund.ku.dk,2025-12-22 15:27:51.869135+00:00,b8c635d1-df46-4e78-9efe-f10dbb35eccb
...,...,...,...,...,...,...,...,...,...,...
155,801440,AGTACTCATG+ACAGTAAGAT,241008_A00706_0886_AHMGK3DSXC_FASTQ.lanebarcod...,4,HMGK3DSXC,101,Nova Seq 6000,julie.bitz-thorsen@sund.ku.dk,2025-12-22 15:27:51.869135+00:00,b8c635d1-df46-4e78-9efe-f10dbb35eccb
156,685020,TGATGGCTAC+CGGTTGTTGG,241008_A00706_0886_AHMGK3DSXC_FASTQ.lanebarcod...,4,HMGK3DSXC,101,Nova Seq 6000,julie.bitz-thorsen@sund.ku.dk,2025-12-22 15:27:51.869135+00:00,b8c635d1-df46-4e78-9efe-f10dbb35eccb
157,577980,GAACGCAATA+ACCACGACAT,241008_A00706_0886_AHMGK3DSXC_FASTQ.lanebarcod...,4,HMGK3DSXC,101,Nova Seq 6000,julie.bitz-thorsen@sund.ku.dk,2025-12-22 15:27:51.869135+00:00,b8c635d1-df46-4e78-9efe-f10dbb35eccb
158,559840,TTCTGTAGAA+GCTTGCGCTC,241008_A00706_0886_AHMGK3DSXC_FASTQ.lanebarcod...,4,HMGK3DSXC,101,Nova Seq 6000,julie.bitz-thorsen@sund.ku.dk,2025-12-22 15:27:51.869135+00:00,b8c635d1-df46-4e78-9efe-f10dbb35eccb
159,504080,TCAATGGAGA+GGTGGAGTGC,241008_A00706_0886_AHMGK3DSXC_FASTQ.lanebarcod...,4,HMGK3DSXC,101,Nova Seq 6000,julie.bitz-thorsen@sund.ku.dk,2025-12-22 15:27:51.869135+00:00,b8c635d1-df46-4e78-9efe-f10dbb35eccb