In [90]:
import os
import pandas as pd

In [91]:
dir_path = r"C:\Users\glj523\Downloads\lanebarcode\lanebarcode"

In [92]:
file_names = os.listdir(dir_path)
df = pd.DataFrame(file_names)

In [93]:
df.rename(columns={0: 'filename'}, inplace=True)

In [94]:
for row in df.iterrows():
    split = row[1]['filename'].split('.')
    if split[1:] != ['lanebarcode', 'html']:
        raise ValueError(f"Unexpected file format: {row[1]['filename']}")
    else :
        df.at[row[0], 'run'] = split[0]

In [95]:
df['date'] = df['run'].apply(lambda x: x.split('_')[0])

In [96]:
df

,filename,run,date
0,20241106_A00706_0891_AHK27KDRX5.lanebarcode.html,20241106_A00706_0891_AHK27KDRX5,20241106
1,20241106_A00706_0892_BH5CTKDSX7.lanebarcode.html,20241106_A00706_0892_BH5CTKDSX7,20241106
2,20241108_A00706_0893_AH5CVTDSX7.lanebarcode.html,20241108_A00706_0893_AH5CVTDSX7,20241108
3,20241129_A00706_0894_BH5FLYDSX7.lanebarcode.html,20241129_A00706_0894_BH5FLYDSX7,20241129
4,20241129_A00706_0895_AHKVJGDRX5.lanebarcode.html,20241129_A00706_0895_AHKVJGDRX5,20241129
...,...,...,...
216,240926_A00706_0885_AH5FHKDSX7_TTS56_ITXBC.lane...,240926_A00706_0885_AH5FHKDSX7_TTS56_ITXBC,240926
217,241008_A00706_0886_AHMGK3DSXC_FASTQ.lanebarcod...,241008_A00706_0886_AHMGK3DSXC_FASTQ,241008
218,241011_A00706_0887_AHMFH5DSXC_HL8MP.lanebarcod...,241011_A00706_0887_AHMFH5DSXC_HL8MP,241011
219,241015_A00706_0889_AHVJTCDSXC_YLP56.lanebarcod...,241015_A00706_0889_AHVJTCDSXC_YLP56,241015
220,241022_A00706_0890_AHJMM2DRX5_CXFTJ_CXHVL.lane...,241022_A00706_0890_AHJMM2DRX5_CXFTJ_CXHVL,241022

In [97]:
df['date'] = df['date'].apply(lambda x: x[2:] if len(x) == 8 else x)

In [98]:
df['machine'] = df['run'].apply(lambda x: x.split('_')[1])

In [99]:
df['run_no'] = df['run'].apply(lambda x: x.split('_')[2])

In [100]:
df['side'] = df['run'].apply(lambda x: x.split('_')[3][0])
df['flowcell'] = df['run'].apply(lambda x: x.split('_')[3][1:])

In [101]:
df.machine.apply(len).value_counts()

machine
6    221
Name: count, dtype: int64

In [102]:
df.astype(str).map(len).date.value_counts()

date
6    221
Name: count, dtype: int64

In [103]:
df

,filename,run,date,machine,run_no,side,flowcell
0,20241106_A00706_0891_AHK27KDRX5.lanebarcode.html,20241106_A00706_0891_AHK27KDRX5,241106,A00706,0891,A,HK27KDRX5
1,20241106_A00706_0892_BH5CTKDSX7.lanebarcode.html,20241106_A00706_0892_BH5CTKDSX7,241106,A00706,0892,B,H5CTKDSX7
2,20241108_A00706_0893_AH5CVTDSX7.lanebarcode.html,20241108_A00706_0893_AH5CVTDSX7,241108,A00706,0893,A,H5CVTDSX7
3,20241129_A00706_0894_BH5FLYDSX7.lanebarcode.html,20241129_A00706_0894_BH5FLYDSX7,241129,A00706,0894,B,H5FLYDSX7
4,20241129_A00706_0895_AHKVJGDRX5.lanebarcode.html,20241129_A00706_0895_AHKVJGDRX5,241129,A00706,0895,A,HKVJGDRX5
...,...,...,...,...,...,...,...
216,240926_A00706_0885_AH5FHKDSX7_TTS56_ITXBC.lane...,240926_A00706_0885_AH5FHKDSX7_TTS56_ITXBC,240926,A00706,0885,A,H5FHKDSX7
217,241008_A00706_0886_AHMGK3DSXC_FASTQ.lanebarcod...,241008_A00706_0886_AHMGK3DSXC_FASTQ,241008,A00706,0886,A,HMGK3DSXC
218,241011_A00706_0887_AHMFH5DSXC_HL8MP.lanebarcod...,241011_A00706_0887_AHMFH5DSXC_HL8MP,241011,A00706,0887,A,HMFH5DSXC
219,241015_A00706_0889_AHVJTCDSXC_YLP56.lanebarcod...,241015_A00706_0889_AHVJTCDSXC_YLP56,241015,A00706,0889,A,HVJTCDSXC
220,241022_A00706_0890_AHJMM2DRX5_CXFTJ_CXHVL.lane...,241022_A00706_0890_AHJMM2DRX5_CXFTJ_CXHVL,241022,A00706,0890,A,HJMM2DRX5

In [104]:
all(df.iloc[:, 2:].astype(str).map(len).nunique() == 1)

True

In [105]:
def find_valid_elements(path):
        path_split = path.split('_')
        res = []
        for ele in path_split:
            if len(ele)== 5 and not any(x.islower() for x in ele):
                res.append(ele)
        if len(res) > 0:
            return res
        else:
            return None

In [106]:
df['ttags'] = df.run.apply(find_valid_elements)

In [107]:
mask = (df.ttags.str.len() > 1) | df.ttags.isna()

In [108]:
helpr_path = r"C:\Users\glj523\Downloads\Copy of list_all_SeqRuns_2024-2025_edit251030JBT.xlsx"

In [109]:
helpr = pd.read_excel(helpr_path)

In [110]:
df['full_flowcell_id'] = df['side'] + df['flowcell']

In [111]:
helpr['full_flowcell_id'] = helpr['InstrumentSide'] + helpr['FlowCellID']

In [112]:
# We don't expect to have multiple ttags unless the RunSheetID contains 'xp'
mask = helpr['RunSheetID'].apply(lambda x: 'xp' in x.lower() if isinstance(x, str) else x)
helpr['RunSheetID_contains_xp'] = mask

In [114]:
mask = helpr['full_flowcell_id'].duplicated(keep=False)

In [115]:
helpr['duplicate_flowcell'] = mask

In [116]:
mask = helpr['duplicate_flowcell'] & ~helpr['RunSheetID_contains_xp']
helpr[mask].sort_values('full_flowcell_id').to_csv(r'Copy of list_all_SeqRuns_2024-2025_edit251030JBT_duplicated.csv', index=False)

In [117]:
helpr[mask].sort_values('full_flowcell_id')

,ID,BSSHRunID,WorkingID,RunSheetID,RunDate,InstrumentID,FlowCellID,InstrumentSide,SequencingOK,full_flowcell_id,RunSheetID_contains_xp,duplicate_flowcell
183,77,240227_A00706_0833_AH35MFDSX7,240221_BWDQD_Zaruhi,240226_Runsheet_S4_100PEDI_A00706_RunA,2024-02-27,A00706,H35MFDSX7,A,True,AH35MFDSX7,False,True
182,78,240227_A00706_0833_AH35MFDSX7,240221_BWDQD_Zaruhi,240507_Runsheet_S4_100PE_A00706_RunA,2024-02-27,A00706,H35MFDSX7,A,True,AH35MFDSX7,False,True
181,162,240227_A00706_0833_AH35MFDSX7,240221_BWDQD_Zaruhi,240226_Runsheet_S4_100PEDI_A00706_RunA,2024-02-27,A00706,H35MFDSX7,A,True,AH35MFDSX7,False,True
141,63,240709_A00706_0865_AH5FCGDSX7,240628_BBN2F_Maria,240709_S4FCA,2024-07-09,A00706,H5FCGDSX7,A,True,AH5FCGDSX7,False,True
140,181,240709_A00706_0865_AH5FCGDSX7,240628_BBN2F_Maria,240709_S4FCA,2024-07-09,A00706,H5FCGDSX7,A,True,AH5FCGDSX7,False,True
46,368,250630_A00706_0949_AHH72YDSXF,250502_THN45_Yucheng,250630_S4FCA,2025-06-30,A00706,HH72YDSXF,A,True,AHH72YDSXF,False,True
47,367,250630_A00706_0949_AHH72YDSXF,250502_THN45_Yucheng,250630_S4FCA,2025-06-30,A00706,HH72YDSXF,A,True,AHH72YDSXF,False,True
152,88,240515_A00706_0858_AHHGJVDSXC,240131_TUB01_Nikoline,240515_RunSheet_S4_150PEDI_A00706_RunA,2024-05-15,A00706,HHGJVDSXC,A,True,AHHGJVDSXC,False,True
151,159,240515_A00706_0858_AHHGJVDSXC,240131_E8KTD_Nikoline,240515_RunSheet_S4_150PEDI_A00706_RunA,2024-05-15,A00706,HHGJVDSXC,A,True,AHHGJVDSXC,False,True
127,195,240916_A00706_0879_AHHVLVDSXC,240821_I5R2U_Xihan,240916_S4FCA,2024-09-16,A00706,HHVLVDSXC,A,True,AHHVLVDSXC,False,True
126,196,240916_A00706_0879_AHHVLVDSXC,240821_J5U5X_Xihan,240916_S4FCA,2024-09-16,A00706,HHVLVDSXC,A,True,AHHVLVDSXC,False,True
217,141,240126_A00706_0811_AHTMW2DSX5,231204_BNW8A_Zaruhi,240126_Runsheet_S4_100PEDI_A00706_RunA,2024-01-26,A00706,HTMW2DSX5,A,True,AHTMW2DSX5,False,True
218,37,240126_A00706_0811_AHTMW2DSX5,240118_ZTM3M_Maria,240126_Runsheet_S4_100PEDI_A00706_RunA,2024-01-26,A00706,HTMW2DSX5,A,True,AHTMW2DSX5,False,True
211,158,240202_A00706_0816_AHTNTGDSX5,240124_MYUGL_Zaruhi,240202_Runsheet_S4_100PEDI_A00706_RunA,2024-02-02,A00706,HTNTGDSX5,A,True,AHTNTGDSX5,False,True
213,54,240202_A00706_0816_AHTNTGDSX5,240126_TUB02_Zaruhi,240202_Runsheet_S4_100PEDI_A00706_RunA,2024-02-02,A00706,HTNTGDSX5,A,True,AHTNTGDSX5,False,True
212,156,240202_A00706_0816_AHTNTGDSX5,240124_SYBP6_Zaruhi,240202_Runsheet_S4_100PEDI_A00706_RunA,2024-02-02,A00706,HTNTGDSX5,A,True,AHTNTGDSX5,False,True
57,352,250618_A00706_0940_AHVTGWDSXC,250520_AZU8V_Xihan,250618_S4FCA,2025-06-18,A00706,HVTGWDSXC,A,True,AHVTGWDSXC,False,True
56,353,250618_A00706_0940_AHVTGWDSXC,250520_AZU8V_Takahiro,250618_S4FCA,2025-06-18,A00706,HVTGWDSXC,A,True,AHVTGWDSXC,False,True
70,322,250228_A00706_0920_AHVV5FDSXC,250205_QHCLV_Suzan,250228_S4FCA,2025-02-28,A00706,HVV5FDSXC,A,True,AHVV5FDSXC,False,True
69,328,250228_A00706_0920_AHVV5FDSXC,250207_XJCRN_Yucheng,250228_S4FCA,2025-02-28,A00706,HVV5FDSXC,A,True,AHVV5FDSXC,False,True
76,311,250219_A00706_0914_AHVVLWDSXC,250127_24M2E_Anap,250219_S4FCA,2025-02-19,A00706,HVVLWDSXC,A,True,AHVVLWDSXC,False,True
75,316,250219_A00706_0914_AHVVLWDSXC,250127_24M2E_Caeg,250219_S4FCA,2025-02-19,A00706,HVVLWDSXC,A,True,AHVVLWDSXC,False,True
60,338,250423_A00706_0929_AHVVN7DSXC,250402_DGCRS_Vlatka,250423_S4FCA,2025-04-23,A00706,HVVN7DSXC,A,True,AHVVN7DSXC,False,True
59,358,250423_A00706_0929_AHVVN7DSXC,250402_DGCRS_Vlatkaii,250403_S4CFA,2025-04-23,A00706,HVVN7DSXC,A,True,AHVVN7DSXC,False,True
175,67,240229_A00706_0835_BH32VNDSX7,240216_SS4ED_Suzan,240228_Runsheet_S4_100PEDI_A00706_RunB,2024-02-29,A00706,H32VNDSX7,B,True,BH32VNDSX7,False,True
174,171,240229_A00706_0835_BH32VNDSX7,240216_SS4ED_Suzan,240228_Runsheet_S4_100PEDI_A00706_RunB,2024-02-29,A00706,H32VNDSX7,B,True,BH32VNDSX7,False,True
166,173,240315_A00706_0844_BH37VGDSX7,240221_ZWT6V_Zaruhi,240315_RunSheet_S4_100PEDI_A00706_RunB,2024-03-15,A00706,H37VGDSX7,B,True,BH37VGDSX7,False,True
167,76,240315_A00706_0844_BH37VGDSX7,240221_ZWT6V_Zaruhi,240315_RunSheet_S4_100PEDI_A00706_RunB,2024-03-15,A00706,H37VGDSX7,B,True,BH37VGDSX7,False,True
165,93,240318_A00706_0845_BH3C37DSX7,240227_X4BL7_Zaruhi,240318_Runsheet_S4_100PEDI_A00706_RunB,2024-03-18,A00706,H3C37DSX7,B,True,BH3C37DSX7,False,True
164,175,240318_A00706_0845_BH3C37DSX7,240227_X4BL7_Zaruhi,240318_Runsheet_S4_100PEDI_A00706_RunB,2024-03-18,A00706,H3C37DSX7,B,True,BH3C37DSX7,False,True
170,172,240311_A00706_0840_BH3CFWDSX7,240221_OWLWN_Zaruhi,240311_RunSheet_S4_100PEDI_A00706_RunB,2024-03-11,A00706,H3CFWDSX7,B,True,BH3CFWDSX7,False,True
171,75,240311_A00706_0840_BH3CFWDSX7,240221_OWLWN_Zaruhi,240311_RunSheet_S4_100PEDI_A00706_RunB,2024-03-11,A00706,H3CFWDSX7,B,True,BH3CFWDSX7,False,True
90,292,250110_A00706_0904_BH5FC5DSX7,241223_ACGTD_Suzan,250110_S4FCB,2025-01-10,A00706,H5FC5DSX7,B,True,BH5FC5DSX7,False,True
89,366,250110_A00706_0904_BH5FC5DSX7,241223_ACGTD_Suzan,250110_S4FCB,2025-01-10,A00706,H5FC5DSX7,B,True,BH5FC5DSX7,False,True
161,81,240322_A00706_0850_BH5FHNDSX7,240307_VHKYZ_Xihan,240322_Runsheet_S4_100PEDI_A00706_RunB,2024-03-22,A00706,H5FHNDSX7,B,True,BH5FHNDSX7,False,True
160,176,240322_A00706_0850_BH5FHNDSX7,240307_VHKYZ_Xihan,240322_Runsheet_S4_100PEDI_A00706_RunB,2024-03-22,A00706,H5FHNDSX7,B,True,BH5FHNDSX7,False,True
5,420,251006_A00706_0980_BHHNHVDSXF,250905_PCOZJ_Mikkel,251006_S4FCB,2025-10-06,A00706,HHNHVDSXF,B,True,BHHNHVDSXF,False,True
4,421,251006_A00706_0980_BHHNHVDSXF,250905_PCOZJ_Irene,251006_S4FCB,2025-10-06,A00706,HHNHVDSXF,B,True,BHHNHVDSXF,False,True
208,157,240202_A00706_0817_BHTT3LDSX5,240124_SYBP6_Zaruhi,240202_Runsheet_S4_100PEDI_A00706_RunB,2024-02-02,A00706,HTT3LDSX5,B,True,BHTT3LDSX5,False,True
209,140,240202_A00706_0817_BHTT3LDSX5,240124_MYUGL_Zaruhi,240202_Runsheet_S4_100PEDI_A00706_RunB,2024-02-02,A00706,HTT3LDSX5,B,True,BHTT3LDSX5,False,True
210,55,240202_A00706_0817_BHTT3LDSX5,240126_TUB02_Zaruhi,240202_Runsheet_S4_100PEDI_A00706_RunA,2024-02-02,A00706,HTT3LDSX5,B,True,BHTT3LDSX5,False,True
105,266,241015_A00706_0888_BHVCGGDSXC,240916_YZQ2X_Claus,241015_S4FCB,2024-10-15,A00706,HVCGGDSXC,B,True,BHVCGGDSXC,False,True
104,218,241015_A00706_0888_BHVCGGDSXC,240916_YZQ2X_Blaine,241015_S4FCB,2024-10-15,A00706,HVCGGDSXC,B,True,BHVCGGDSXC,False,True

In [86]:
mask = df['full_flowcell_id'].duplicated(keep=False)
df[mask].sort_values('full_flowcell_id').to_csv('duplicated_lanebarcodes.csv', index=False)

In [ ]:
merged_df = df.merge(helpr, on='full_flowcell_id', how='outer', indicator=True)

In [24]:
trans = {'left_only': 'Only found in lanebarcode filenames',
         'right_only': 'Only found in excel sheet',
         'both': 'Found in both lanebarcode filenames and excel sheet'}
merged_df['_merge'] = merged_df['_merge'].apply(lambda x: trans[x])
merged_df = merged_df.rename(columns={'_merge': 'flowcell_id_source'})

In [25]:
from pathlib import Path
import sys
import os

def find_project_root():
    path = Path(os.getcwd()).resolve()
    while path != path.root:
        if (path / 'very_rootsy_file.txt').exists():
            return path
        path = path.parent
    return None  # Project root not found

project_root = find_project_root()

sys.path.append(str(project_root))

In [26]:
%env PGPASSWORD=5J8DhII0RRsPW1

env: PGPASSWORD=5J8DhII0RRsPW1

In [27]:
from constants.db_connections import ENGINE, ENGINE_READ_ONLY, SQL_ALCH_CONFIG, PSY_CONN
q = 'select * from flowcell'
db = pd.read_sql(q, ENGINE_READ_ONLY)
db['full_flowcell_id'] = db['flowcell_position'] + db['flowcell_id']
m3 = merged_df['full_flowcell_id'].isin(db['full_flowcell_id'].unique())
merged_df['in_db'] = m3

In [ ]:
mask = (merged_df['RunSheetID_contains_xp'] == False) & (merged_df.ttags.apply(lambda x: isinstance(x, list) and len(x) > 1))
merged_df['ttag_count_issue'] = mask

In [32]:
mask = (merged_df['in_db'] == False) & (merged_df['RunSheetID_contains_xp'] == False) & (merged_df['flowcell_id_source'] == 'Found in both lanebarcode filenames and excel sheet') & (merged_df['ttag_count_issue'] == False)
merged_df['upload_to_db'] = mask

In [33]:
mask = merged_df['upload_to_db']
upload_to_db = merged_df[mask]

Get all lanebarcode data to upload into one df

In [34]:
from constants.db_names.names import data
import lane_barcode_parser

fc = []
tpb = []

for file_name in upload_to_db.filename:
    file_path = os.path.join(dir_path, file_name)

    tube_tag_col_name = data.flowcell.library_pool_tag()
    read_len_col_name = data.flowcell.read_length()
    seq_machine_col_name = data.flowcell.sequencing_machine()
    seq_date_col_name = data.flowcell.sequencing_date()
    flowcell_pos_col_name = data.flowcell.flowcell_position()
    seq_run_col_name = data.flowcell.sequencing_run()


    # TODO: Make more general:
    sheet = pd.read_html(file_path, thousands=',', decimal='.')

    flowcell_data, top_unknown_barcodes = lane_barcode_parser.parse(df=sheet)

    fc.append(flowcell_data)
    tpb.append(top_unknown_barcodes)

In [35]:
flowcell_data = pd.concat(fc, ignore_index=True)
top_unknown_barcodes = pd.concat(tpb, ignore_index=True)

Get read length, sequencing date, tubetag, seq machine, seq run and flowcell pos merged in

In [38]:
upload_to_db

,filename,run,date,machine,run_no,side,flowcell,ttags,full_flowcell_id,ID,...,RunDate,InstrumentID,FlowCellID,InstrumentSide,SequencingOK,flowcell_id_source,in_db,RunSheetID_contains_xp,ttag_count_issue,upload_to_db
3,240219_A00706_0829_AH32TTDSX7_606A.lanebarcode...,240219_A00706_0829_AH32TTDSX7_606A,240219,A00706,0829,A,H32TTDSX7,None,AH32TTDSX7,8.0,...,2024-02-19,A00706,H32TTDSX7,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
16,240212_A00706_0822_AH35MMDSX7_G8HU5.lanebarcod...,240212_A00706_0822_AH35MMDSX7_G8HU5,240212,A00706,0822,A,H35MMDSX7,[G8HU5],AH35MMDSX7,3.0,...,2024-02-12,A00706,H35MMDSX7,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
18,240216_A00706_0826_AH3725DSX7_L8R4I.lanebarcod...,240216_A00706_0826_AH3725DSX7_L8R4I,240216,A00706,0826,A,H3725DSX7,[L8R4I],AH3725DSX7,5.0,...,2024-02-16,A00706,H3725DSX7,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
19,240216_A00706_0826_AH3725DSX7_L8R4I_reDMPX.lan...,240216_A00706_0826_AH3725DSX7_L8R4I_reDMPX,240216,A00706,0826,A,H3725DSX7,[L8R4I],AH3725DSX7,5.0,...,2024-02-16,A00706,H3725DSX7,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
20,240216_A00706_0826_AH3725DSX7_L8R4I_reDMPX_new...,240216_A00706_0826_AH3725DSX7_L8R4I_reDMPX_new,240216,A00706,0826,A,H3725DSX7,[L8R4I],AH3725DSX7,5.0,...,2024-02-16,A00706,H3725DSX7,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
34,20241108_A00706_0893_AH5CVTDSX7.lanebarcode.html,20241108_A00706_0893_AH5CVTDSX7,241108,A00706,0893,A,H5CVTDSX7,None,AH5CVTDSX7,267.0,...,2024-11-08,A00706,H5CVTDSX7,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
36,240801_A00706_0873_AH5CY7DSX7_E5VBT.lanebarcod...,240801_A00706_0873_AH5CY7DSX7_E5VBT,240801,A00706,0873,A,H5CY7DSX7,[E5VBT],AH5CY7DSX7,188.0,...,2024-08-01,A00706,H5CY7DSX7,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
40,240621_A00706_0860_AH5F3TDSX7_L5WAS.lanebarcod...,240621_A00706_0860_AH5F3TDSX7_L5WAS,240621,A00706,0860,A,H5F3TDSX7,[L5WAS],AH5F3TDSX7,86.0,...,2024-06-21,A00706,H5F3TDSX7,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
41,20250117_A00706_0910_AH5F73DSX7.lanebarcode.html,20250117_A00706_0910_AH5F73DSX7,250117,A00706,0910,A,H5F73DSX7,None,AH5F73DSX7,302.0,...,2025-01-17,A00706,H5F73DSX7,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
44,240507_A00706_0857_AH5FC2DSX7_BWDQD.lanebarcod...,240507_A00706_0857_AH5FC2DSX7_BWDQD,240507,A00706,0857,A,H5FC2DSX7,[BWDQD],AH5FC2DSX7,174.0,...,2024-05-07,A00706,H5FC2DSX7,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
45,20250108_A00706_0903_AH5FC3DSX7.lanebarcode.html,20250108_A00706_0903_AH5FC3DSX7,250108,A00706,0903,A,H5FC3DSX7,None,AH5FC3DSX7,289.0,...,2025-01-08,A00706,H5FC3DSX7,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
46,20250115_A00706_0908_AH5FCCDSX7.lanebarcode.html,20250115_A00706_0908_AH5FCCDSX7,250115,A00706,0908,A,H5FCCDSX7,None,AH5FCCDSX7,295.0,...,2025-01-15,A00706,H5FCCDSX7,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
47,240709_A00706_0865_AH5FCGDSX7_BBN2F.lanebarcod...,240709_A00706_0865_AH5FCGDSX7_BBN2F,240709,A00706,0865,A,H5FCGDSX7,[BBN2F],AH5FCGDSX7,181.0,...,2024-07-09,A00706,H5FCGDSX7,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
48,240709_A00706_0865_AH5FCGDSX7_BBN2F.lanebarcod...,240709_A00706_0865_AH5FCGDSX7_BBN2F,240709,A00706,0865,A,H5FCGDSX7,[BBN2F],AH5FCGDSX7,63.0,...,2024-07-09,A00706,H5FCGDSX7,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
49,20250106_A00706_0901_AH5FCWDSX7.lanebarcode.html,20250106_A00706_0901_AH5FCWDSX7,250106,A00706,0901,A,H5FCWDSX7,None,AH5FCWDSX7,285.0,...,2025-01-06,A00706,H5FCWDSX7,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
50,240913_A00706_0877_AH5FFCDSX7_77MZJ.lanebarcod...,240913_A00706_0877_AH5FFCDSX7_77MZJ,240913,A00706,0877,A,H5FFCDSX7,[77MZJ],AH5FFCDSX7,197.0,...,2024-09-13,A00706,H5FFCDSX7,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
53,240730_A00706_0870_AH5FG5DSX7_QQESO.lanebarcod...,240730_A00706_0870_AH5FG5DSX7_QQESO,240730,A00706,0870,A,H5FG5DSX7,[QQESO],AH5FG5DSX7,186.0,...,2024-07-30,A00706,H5FG5DSX7,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
57,20250103_A00706_0898_AH5FMHDSX7.lanebarcode.html,20250103_A00706_0898_AH5FMHDSX7,250103,A00706,0898,A,H5FMHDSX7,None,AH5FMHDSX7,283.0,...,2025-01-03,A00706,H5FMHDSX7,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
59,20250307_A00706_0924_AH72L5DSXF.lanebarcode.html,20250307_A00706_0924_AH72L5DSXF,250307,A00706,0924,A,H72L5DSXF,None,AH72L5DSXF,325.0,...,2025-03-07,A00706,H72L5DSXF,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
84,240515_A00706_0858_AHHGJVDSXC_Nikoline_E8KTD.l...,240515_A00706_0858_AHHGJVDSXC_Nikoline_E8KTD,240515,A00706,0858,A,HHGJVDSXC,[E8KTD],AHHGJVDSXC,159.0,...,2024-05-15,A00706,HHGJVDSXC,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
85,240515_A00706_0858_AHHGJVDSXC_Nikoline_E8KTD.l...,240515_A00706_0858_AHHGJVDSXC_Nikoline_E8KTD,240515,A00706,0858,A,HHGJVDSXC,[E8KTD],AHHGJVDSXC,88.0,...,2024-05-15,A00706,HHGJVDSXC,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
106,240724_A00706_0868_AHL577DSXC_LPNV6_Anna.laneb...,240724_A00706_0868_AHL577DSXC_LPNV6_Anna,240724,A00706,0868,A,HL577DSXC,[LPNV6],AHL577DSXC,182.0,...,2024-07-24,A00706,HL577DSXC,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
107,241011_A00706_0887_AHMFH5DSXC_HL8MP.lanebarcod...,241011_A00706_0887_AHMFH5DSXC_HL8MP,241011,A00706,0887,A,HMFH5DSXC,[HL8MP],AHMFH5DSXC,212.0,...,2024-10-11,A00706,HMFH5DSXC,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
162,240126_A00706_0811_AHTMW2DSX5_603A.lanebarcode...,240126_A00706_0811_AHTMW2DSX5_603A,240126,A00706,0811,A,HTMW2DSX5,None,AHTMW2DSX5,141.0,...,2024-01-26,A00706,HTMW2DSX5,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
163,240126_A00706_0811_AHTMW2DSX5_603A.lanebarcode...,240126_A00706_0811_AHTMW2DSX5_603A,240126,A00706,0811,A,HTMW2DSX5,None,AHTMW2DSX5,37.0,...,2024-01-26,A00706,HTMW2DSX5,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
178,241015_A00706_0889_AHVJTCDSXC_YLP56.lanebarcod...,241015_A00706_0889_AHVJTCDSXC_YLP56,241015,A00706,0889,A,HVJTCDSXC,[YLP56],AHVJTCDSXC,217.0,...,2024-10-15,A00706,HVJTCDSXC,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
181,20250415_A00706_0927_AHVV3CDSXC.lanebarcode.html,20250415_A00706_0927_AHVV3CDSXC,250415,A00706,0927,A,HVV3CDSXC,None,AHVV3CDSXC,332.0,...,2025-04-15,A00706,HVV3CDSXC,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
183,20250311_A00706_0925_AHVV52DSXC.lanebarcode.html,20250311_A00706_0925_AHVV52DSXC,250311,A00706,0925,A,HVV52DSXC,None,AHVV52DSXC,331.0,...,2025-03-11,A00706,HVV52DSXC,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
187,20250219_A00706_0914_AHVVLWDSXC.lanebarcode.html,20250219_A00706_0914_AHVVLWDSXC,250219,A00706,0914,A,HVVLWDSXC,None,AHVVLWDSXC,316.0,...,2025-02-19,A00706,HVVLWDSXC,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
188,20250219_A00706_0914_AHVVLWDSXC.lanebarcode.html,20250219_A00706_0914_AHVVLWDSXC,250219,A00706,0914,A,HVVLWDSXC,None,AHVVLWDSXC,311.0,...,2025-02-19,A00706,HVVLWDSXC,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
189,20250219_A00706_0914_AHVVLWDSXC_eDNAlib108.lan...,20250219_A00706_0914_AHVVLWDSXC_eDNAlib108,250219,A00706,0914,A,HVVLWDSXC,None,AHVVLWDSXC,316.0,...,2025-02-19,A00706,HVVLWDSXC,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
190,20250219_A00706_0914_AHVVLWDSXC_eDNAlib108.lan...,20250219_A00706_0914_AHVVLWDSXC_eDNAlib108,250219,A00706,0914,A,HVVLWDSXC,None,AHVVLWDSXC,311.0,...,2025-02-19,A00706,HVVLWDSXC,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
192,20250423_A00706_0929_AHVVN7DSXC.lanebarcode.html,20250423_A00706_0929_AHVVN7DSXC,250423,A00706,0929,A,HVVN7DSXC,None,AHVVN7DSXC,358.0,...,2025-04-23,A00706,HVVN7DSXC,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
193,20250423_A00706_0929_AHVVN7DSXC.lanebarcode.html,20250423_A00706_0929_AHVVN7DSXC,250423,A00706,0929,A,HVVN7DSXC,None,AHVVN7DSXC,338.0,...,2025-04-23,A00706,HVVN7DSXC,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
201,240212_A00706_0823_BH32YKDSX7_E8JW7.lanebarcod...,240212_A00706_0823_BH32YKDSX7_E8JW7,240212,A00706,0823,B,H32YKDSX7,[E8JW7],BH32YKDSX7,4.0,...,2024-02-12,A00706,H32YKDSX7,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
203,240219_A00706_0828_BH37V3DSX7_607B.lanebarcode...,240219_A00706_0828_BH37V3DSX7_607B,240219,A00706,0828,B,H37V3DSX7,None,BH37V3DSX7,10.0,...,2024-02-19,A00706,H37V3DSX7,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
230,20241106_A00706_0892_BH5CTKDSX7.lanebarcode.html,20241106_A00706_0892_BH5CTKDSX7,241106,A00706,0892,B,H5CTKDSX7,None,BH5CTKDSX7,268.0,...,2024-11-06,A00706,H5CTKDSX7,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
231,20250103_A00706_0899_BH5CVCDSX7.lanebarcode.html,20250103_A00706_0899_BH5CVCDSX7,250103,A00706,0899,B,H5CVCDSX7,None,BH5CVCDSX7,284.0,...,2025-01-03,A00706,H5CVCDSX7,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
232,240806_A00706_0874_BH5CVHDSX7_I7KZE.lanebarcod...,240806_A00706_0874_BH5CVHDSX7_I7KZE,240806,A00706,0874,B,H5CVHDSX7,[I7KZE],BH5CVHDSX7,191.0,...,2024-08-06,A00706,H5CVHDSX7,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
233,240924_A00706_0882_BH5CW5DSX7_AMT6F.lanebarcod...,240924_A00706_0882_BH5CW5DSX7_AMT6F,240924,A00706,0882,B,H5CW5DSX7,[AMT6F],BH5CW5DSX7,204.0,...,2024-09-24,A00706,H5CW5DSX7,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
234,240916_A00706_0878_BH5CWLDSX7_BMBMU.lanebarcod...,240916_A00706_0878_BH5CWLDSX7_BMBMU,240916,A00706,0878,B,H5CWLDSX7,[BMBMU],BH5CWLDSX7,205.0,...,2024-09-16,A00706,H5CWLDSX7,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
235,240724_A00706_0869_BH5F2GDSX7_PQFUO.lanebarcod...,240724_A00706_0869_BH5F2GDSX7_PQFUO,240724,A00706,0869,B,H5F2GDSX7,[PQFUO],BH5F2GDSX7,185.0,...,2024-07-24,A00706,H5F2GDSX7,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
236,240724_A00706_0869_BH5F2GDSX7_PQFUO_Marina.lan...,240724_A00706_0869_BH5F2GDSX7_PQFUO_Marina,240724,A00706,0869,B,H5F2GDSX7,[PQFUO],BH5F2GDSX7,185.0,...,2024-07-24,A00706,H5F2GDSX7,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
247,20250110_A00706_0904_BH5FC5DSX7.lanebarcode.html,20250110_A00706_0904_BH5FC5DSX7,250110,A00706,0904,B,H5FC5DSX7,None,BH5FC5DSX7,366.0,...,2025-01-10,A00706,H5FC5DSX7,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
248,20250110_A00706_0904_BH5FC5DSX7.lanebarcode.html,20250110_A00706_0904_BH5FC5DSX7,250110,A00706,0904,B,H5FC5DSX7,None,BH5FC5DSX7,292.0,...,2025-01-10,A00706,H5FC5DSX7,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
249,240918_A00706_0880_BH5FCMDSX7_ZMXBJ.lanebarcod...,240918_A00706_0880_BH5FCMDSX7_ZMXBJ,240918,A00706,0880,B,H5FCMDSX7,[ZMXBJ],BH5FCMDSX7,206.0,...,2024-09-18,A00706,H5FCMDSX7,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
250,240704_A00706_0864_BH5FCVDSX7_OBXCQ.lanebarcod...,240704_A00706_0864_BH5FCVDSX7_OBXCQ,240704,A00706,0864,B,H5FCVDSX7,[OBXCQ],BH5FCVDSX7,179.0,...,2024-07-04,A00706,H5FCVDSX7,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
252,20250113_A00706_0907_BH5FG2DSX7.lanebarcode.html,20250113_A00706_0907_BH5FG2DSX7,250113,A00706,0907,B,H5FG2DSX7,None,BH5FG2DSX7,294.0,...,2025-01-13,A00706,H5FG2DSX7,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
253,240801_A00706_0872_BH5FG3DSX7_L53HZ.lanebarcod...,240801_A00706_0872_BH5FG3DSX7_L53HZ,240801,A00706,0872,B,H5FG3DSX7,[L53HZ],BH5FG3DSX7,189.0,...,2024-08-01,A00706,H5FG3DSX7,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
254,20250115_A00706_0909_BH5FG7DSX7.lanebarcode.html,20250115_A00706_0909_BH5FG7DSX7,250115,A00706,0909,B,H5FG7DSX7,None,BH5FG7DSX7,296.0,...,2025-01-15,A00706,H5FG7DSX7,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
256,240730_A00706_0871_BH5FH5DSX7_N54I2.lanebarcod...,240730_A00706_0871_BH5FH5DSX7_N54I2,240730,A00706,0871,B,H5FH5DSX7,[N54I2],BH5FH5DSX7,187.0,...,2024-07-30,A00706,H5FH5DSX7,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
259,20241129_A00706_0894_BH5FLYDSX7.lanebarcode.html,20241129_A00706_0894_BH5FLYDSX7,241129,A00706,0894,B,H5FLYDSX7,None,BH5FLYDSX7,275.0,...,2024-11-29,A00706,H5FLYDSX7,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
281,20250106_A00706_0900_BHCJY7DSX7.lanebarcode.html,20250106_A00706_0900_BHCJY7DSX7,250106,A00706,0900,B,HCJY7DSX7,None,BHCJY7DSX7,287.0,...,2025-01-06,A00706,HCJY7DSX7,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
288,240417_A00706_0854_BHFKVGDSXC_KJCPR.lanebarcod...,240417_A00706_0854_BHFKVGDSXC_KJCPR,240417,A00706,0854,B,HFKVGDSXC,[KJCPR],BHFKVGDSXC,85.0,...,2024-04-17,A00706,HFKVGDSXC,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
332,20250423_A00706_0928_BHVTGVDSXC.lanebarcode.html,20250423_A00706_0928_BHVTGVDSXC,250423,A00706,0928,B,HVTGVDSXC,None,BHVTGVDSXC,339.0,...,2025-04-23,A00706,HVTGVDSXC,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
335,20250122_A00706_0912_BHVV2KDSXC.lanebarcode.html,20250122_A00706_0912_BHVV2KDSXC,250122,A00706,0912,B,HVV2KDSXC,None,BHVV2KDSXC,305.0,...,2025-01-22,A00706,HVV2KDSXC,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
339,20250415_A00706_0926_BHVVTHDSXC.lanebarcode.html,20250415_A00706_0926_BHVVTHDSXC,250415,A00706,0926,B,HVVTHDSXC,None,BHVVTHDSXC,333.0,...,2025-04-15,A00706,HVVTHDSXC,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True

In [42]:
mask = upload_to_db.flowcell.duplicated()
upload_to_db[mask]

,filename,run,date,machine,run_no,side,flowcell,ttags,full_flowcell_id,ID,...,RunDate,InstrumentID,FlowCellID,InstrumentSide,SequencingOK,flowcell_id_source,in_db,RunSheetID_contains_xp,ttag_count_issue,upload_to_db
19,240216_A00706_0826_AH3725DSX7_L8R4I_reDMPX.lan...,240216_A00706_0826_AH3725DSX7_L8R4I_reDMPX,240216,A00706,0826,A,H3725DSX7,[L8R4I],AH3725DSX7,5.0,...,2024-02-16,A00706,H3725DSX7,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
20,240216_A00706_0826_AH3725DSX7_L8R4I_reDMPX_new...,240216_A00706_0826_AH3725DSX7_L8R4I_reDMPX_new,240216,A00706,0826,A,H3725DSX7,[L8R4I],AH3725DSX7,5.0,...,2024-02-16,A00706,H3725DSX7,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
48,240709_A00706_0865_AH5FCGDSX7_BBN2F.lanebarcod...,240709_A00706_0865_AH5FCGDSX7_BBN2F,240709,A00706,0865,A,H5FCGDSX7,[BBN2F],AH5FCGDSX7,63.0,...,2024-07-09,A00706,H5FCGDSX7,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
85,240515_A00706_0858_AHHGJVDSXC_Nikoline_E8KTD.l...,240515_A00706_0858_AHHGJVDSXC_Nikoline_E8KTD,240515,A00706,0858,A,HHGJVDSXC,[E8KTD],AHHGJVDSXC,88.0,...,2024-05-15,A00706,HHGJVDSXC,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
163,240126_A00706_0811_AHTMW2DSX5_603A.lanebarcode...,240126_A00706_0811_AHTMW2DSX5_603A,240126,A00706,0811,A,HTMW2DSX5,None,AHTMW2DSX5,37.0,...,2024-01-26,A00706,HTMW2DSX5,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
188,20250219_A00706_0914_AHVVLWDSXC.lanebarcode.html,20250219_A00706_0914_AHVVLWDSXC,250219,A00706,0914,A,HVVLWDSXC,None,AHVVLWDSXC,311.0,...,2025-02-19,A00706,HVVLWDSXC,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
189,20250219_A00706_0914_AHVVLWDSXC_eDNAlib108.lan...,20250219_A00706_0914_AHVVLWDSXC_eDNAlib108,250219,A00706,0914,A,HVVLWDSXC,None,AHVVLWDSXC,316.0,...,2025-02-19,A00706,HVVLWDSXC,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
190,20250219_A00706_0914_AHVVLWDSXC_eDNAlib108.lan...,20250219_A00706_0914_AHVVLWDSXC_eDNAlib108,250219,A00706,0914,A,HVVLWDSXC,None,AHVVLWDSXC,311.0,...,2025-02-19,A00706,HVVLWDSXC,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
193,20250423_A00706_0929_AHVVN7DSXC.lanebarcode.html,20250423_A00706_0929_AHVVN7DSXC,250423,A00706,0929,A,HVVN7DSXC,None,AHVVN7DSXC,338.0,...,2025-04-23,A00706,HVVN7DSXC,A,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
236,240724_A00706_0869_BH5F2GDSX7_PQFUO_Marina.lan...,240724_A00706_0869_BH5F2GDSX7_PQFUO_Marina,240724,A00706,0869,B,H5F2GDSX7,[PQFUO],BH5F2GDSX7,185.0,...,2024-07-24,A00706,H5F2GDSX7,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True
248,20250110_A00706_0904_BH5FC5DSX7.lanebarcode.html,20250110_A00706_0904_BH5FC5DSX7,250110,A00706,0904,B,H5FC5DSX7,None,BH5FC5DSX7,292.0,...,2025-01-10,A00706,H5FC5DSX7,B,True,Found in both lanebarcode filenames and excel ...,False,False,False,True

In [43]:
mask = merged_df.flowcell.duplicated()
merged_df[mask]

,filename,run,date,machine,run_no,side,flowcell,ttags,full_flowcell_id,ID,...,RunDate,InstrumentID,FlowCellID,InstrumentSide,SequencingOK,flowcell_id_source,in_db,RunSheetID_contains_xp,ttag_count_issue,upload_to_db
6,240229_A00706_0834_AH3332DSX7_XP_2PM2S_BYN4J_H...,240229_A00706_0834_AH3332DSX7_XP_2PM2S_BYN4J_H...,240229,A00706,0834,A,H3332DSX7,"[2PM2S, BYN4J, HYO5K, TYKZG]",AH3332DSX7,169.0,...,2024-02-29,A00706,H3332DSX7,A,True,Found in both lanebarcode filenames and excel ...,False,True,False,False
7,240229_A00706_0834_AH3332DSX7_XP_2PM2S_BYN4J_H...,240229_A00706_0834_AH3332DSX7_XP_2PM2S_BYN4J_H...,240229,A00706,0834,A,H3332DSX7,"[2PM2S, BYN4J, HYO5K, TYKZG]",AH3332DSX7,168.0,...,2024-02-29,A00706,H3332DSX7,A,True,Found in both lanebarcode filenames and excel ...,False,True,False,False
8,240229_A00706_0834_AH3332DSX7_XP_2PM2S_BYN4J_H...,240229_A00706_0834_AH3332DSX7_XP_2PM2S_BYN4J_H...,240229,A00706,0834,A,H3332DSX7,"[2PM2S, BYN4J, HYO5K, TYKZG]",AH3332DSX7,167.0,...,2024-02-29,A00706,H3332DSX7,A,True,Found in both lanebarcode filenames and excel ...,False,True,False,False
9,240229_A00706_0834_AH3332DSX7_XP_2PM2S_BYN4J_H...,240229_A00706_0834_AH3332DSX7_XP_2PM2S_BYN4J_H...,240229,A00706,0834,A,H3332DSX7,"[2PM2S, BYN4J, HYO5K, TYKZG]",AH3332DSX7,12.0,...,2024-02-29,A00706,H3332DSX7,A,True,Found in both lanebarcode filenames and excel ...,False,True,False,False
11,240227_A00706_0833_AH35MFDSX7_BWDQD.lanebarcod...,240227_A00706_0833_AH35MFDSX7_BWDQD,240227,A00706,0833,A,H35MFDSX7,[BWDQD],AH35MFDSX7,78.0,...,2024-02-27,A00706,H35MFDSX7,A,True,Found in both lanebarcode filenames and excel ...,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341,20241211_A00706_0897_BHVWKVDSXC.lanebarcode.html,20241211_A00706_0897_BHVWKVDSXC,241211,A00706,0897,B,HVWKVDSXC,None,BHVWKVDSXC,281.0,...,2024-12-11,A00706,HVWKVDSXC,B,True,Found in both lanebarcode filenames and excel ...,False,True,False,False
342,20241211_A00706_0897_BHVWKVDSXC.lanebarcode.html,20241211_A00706_0897_BHVWKVDSXC,241211,A00706,0897,B,HVWKVDSXC,None,BHVWKVDSXC,280.0,...,2024-12-11,A00706,HVWKVDSXC,B,True,Found in both lanebarcode filenames and excel ...,False,True,False,False
343,20241211_A00706_0897_BHVWKVDSXC.lanebarcode.html,20241211_A00706_0897_BHVWKVDSXC,241211,A00706,0897,B,HVWKVDSXC,None,BHVWKVDSXC,279.0,...,2024-12-11,A00706,HVWKVDSXC,B,True,Found in both lanebarcode filenames and excel ...,False,True,False,False
348,230308_A00706_0708_BHWLFLDRX2_MortenA_TTJ8K_GI...,230308_A00706_0708_BHWLFLDRX2_MortenA_TTJ8K_GIQZB,230308,A00706,0708,B,HWLFLDRX2,"[TTJ8K, GIQZB]",BHWLFLDRX2,NaN,...,NaT,NaN,NaN,NaN,NaN,Only found in lanebarcode filenames,False,NaN,False,False
350,230313_A00706_0711_BHY2V5DRX2_Luke_FSBLI.laneb...,230313_A00706_0711_BHY2V5DRX2_Luke_FSBLI,230313,A00706,0711,B,HY2V5DRX2,[FSBLI],BHY2V5DRX2,NaN,...,NaT,NaN,NaN,NaN,NaN,Only found in lanebarcode filenames,False,NaN,False,False

In [40]:
len(upload_to_db.flowcell.unique())

46

In [36]:
flowcell_data

,Lane,Project,Sample,Barcode sequence,PF Clusters,% of the lane,% Perfect barcode,% One mismatch barcode,Yield (Mbases),% PF Clusters,% >= Q30 bases,Mean Quality Score,Flowcell ID,Clusters (Raw) sum,Clusters(PF) sum,Yield (MBases) sum
0,1,240219-S4-2KESP-Lundbeck-606,018345T-0-LV2001740460-LV7008960548-srri9-E-ve...,TGCCGGTCAG+TTGTATCAGG,32950097,1.14,93.71,6.29,6656,100.0,90.26,35.24,H32TTDSX7,15320088576,11625755847,2348403
1,1,240219-S4-2KESP-Lundbeck-606,020943T-0-LV2001740498-LV7008957428-srri9-E-ve...,CACTCAATTC+CACAACTTAA,27782239,0.96,95.21,4.79,5612,100.0,91.07,35.41,H32TTDSX7,15320088576,11625755847,2348403
2,1,240219-S4-2KESP-Lundbeck-606,021187T-0-LV2001740142-LV7008960572-srri9-E-ve...,TCTCACACGC+TCACTGTCCG,31109882,1.08,96.48,3.52,6284,100.0,90.34,35.25,H32TTDSX7,15320088576,11625755847,2348403
3,1,240219-S4-2KESP-Lundbeck-606,100026T-0-LV2001741423-LV7008960611-srri9-E-ve...,GGACCAGTGG+TAGGCTCGCG,30484361,1.06,95.44,4.56,6158,100.0,89.95,35.18,H32TTDSX7,15320088576,11625755847,2348403
4,1,240219-S4-2KESP-Lundbeck-606,100334T-0-LV2001740006-LV7008960596-srri9-E-ve...,ATATGCATGT+CCAGGCACCA,31398564,1.09,95.16,4.84,6343,100.0,92.15,35.62,H32TTDSX7,15320088576,11625755847,2348403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14071,4,COREX,LV7008865470-LV6000653908-SK2024-8,CCGAAGCGCT+ATAGTTAGCA,44316155,1.41,91.58,8.42,8952,100.0,92.54,35.7,HVVTHDSXC,15320088576,12518579994,2528753
14072,4,COREX,LV7008865471-LV6000653871-SK2024-5,GATCGGATAA+CGGCCGATAC,42779908,1.36,98.07,1.93,8642,100.0,91.48,35.47,HVVTHDSXC,15320088576,12518579994,2528753
14073,4,COREX,LV7008865472-LV6000653903-SK2024-3,GAGGTTAGAC+GCAATACATT,49678862,1.58,97.41,2.59,10035,100.0,93.57,35.9,HVVTHDSXC,15320088576,12518579994,2528753
14074,4,COREX,LV7008865558-LV6000653873-HH2024-1,TAGTGGAAGC+TATAGGTACT,45436718,1.44,96.78,3.22,9178,100.0,92.64,35.72,HVVTHDSXC,15320088576,12518579994,2528753
14075,4,default,Undetermined,unknown,92707146,2.94,100.0,nan,18727,12.06,69.91,30.71,HVVTHDSXC,15320088576,12518579994,2528753