In [1]:
import pandas as pd
import re

pd.set_option('display.max_rows', 700)

In [2]:
df = pd.read_csv(r"n:\SUN-GI-metadb-test\CGG data\query_files\3\query_result_full.csv")

C:\Users\glj523\AppData\Local\Temp\ipykernel_11904\1847043259.py:1: DtypeWarning: Columns (19,23,53,59,60,61,62,64,65,66,67,68,69,70,71,72,73,76,77,78,79,80,81,83,84,85,86,87,88,92,93,95,96,97,98,100,101,102,103,104,107,108,109,110,111,112,113,114,116,117,126,130) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"n:\SUN-GI-metadb-test\CGG data\query_files\3\query_result_full.csv")

In [4]:
df.columns.sort_values()

Index(['% >= Q30 bases', '% One mismatch barcode', '% PF Clusters',
       '% Perfect barcode', '% of the flowcell lane',
       'Age Estimate - from (ka)', 'Age Estimate - to (ka)',
       'ArchiveSampleDepthCalTape', 'ArchiveSampleOrderedDepthCalTape',
       'ArchiveSampleOrganicContent',
       ...
       'flowcell_id', 'i5 Bases in Adapter', 'i7 Bases in Adapter',
       'library_id', 'prod_res_path', 'qPCR Date', 'robot_sample_id',
       'rs_RemarksRobotSampling', 'seq_project_name', 'seqc_tube_tag'],
      dtype='object', length=131)

In [2]:
db = pd.read_csv(r"c:\Users\glj523\Downloads\edna_archive_sample_202410250904.txt", sep="\t", encoding='utf-8', dtype=str)
db["field_sample_id"] = db["field_sample_id"].str.replace("-", "_")
db["field_sample_id"] = db["field_sample_id"].str.replace(" ", "")
db[~db["field_sample_id"].str.match('^CGG_3_\d{6}$')]
db.loc[84, "field_sample_id"] = 'CGG_3_007859'
db = db.rename(columns={"SamplingDate": "ArchiveSamplingDate", "Submitter": "ArchiveSamplingSubmitter", "SubmissionDate": "ArchiveSamplingSubmissionDate"})

db_cgg_ids = db["field_sample_id"].unique()

In [3]:
cgg = pd.read_excel(r"n:\SUN-GI-metadb-test\CGG data\CGG_Database_Sediment_Water_240410_PSO.xlsx", sheet_name="Sediment_Water", dtype=str)
cgg = cgg.dropna(subset=["CGG ID"])
cgg["CGG ID"] = cgg["CGG ID"].str.strip()
cgg["CGG ID"] = cgg["CGG ID"].str.replace("CCG", "CGG")

In [4]:
cgg = cgg[cgg["CGG ID"].isin(db_cgg_ids)]
merged = cgg.merge(db, how="inner", left_on="CGG ID", right_on="field_sample_id")
merged = merged.drop(columns=["field_sample_id"])

In [5]:
cgg[cgg["CGG ID"].duplicated()]

Empty DataFrame
Columns: [CGG ID, Museum ID/sample ID, Lab no., Stock sample left, Extraction#, Extraction date, Kind of Library, Library date, Intern Provider, Sample type, Depth, height (m) asl., Material type, Sampled as, Sample size, Depositional environment, Age, Geological age, Site, Site info, City/town/location, State/province/region, Country, Continent, Lat, Lon, GPS, Sample Provider, Museum/Institution, Contact info, Date collected, Date recieved, Date returned, Sample location, Extraction location, In care of , Date out, Project name, Supervisor, Analyses history, GenBank ref#, Publications, References, Notes, Thawed up, Unnamed: 45, Unnamed: 46, Unnamed: 47, Unnamed: 48, Unnamed: 49, Unnamed: 50, Unnamed: 51, Unnamed: 52, Unnamed: 53, Unnamed: 54, Unnamed: 55, Unnamed: 56, Unnamed: 57, Unnamed: 58, Unnamed: 59, Unnamed: 60, Unnamed: 61, Unnamed: 62, Unnamed: 63, Unnamed: 64, Unnamed: 65, Unnamed: 66, Unnamed: 67, Unnamed: 68, Unnamed: 69, Unnamed: 70, Unnamed: 71, Unnamed: 72, Unnamed: 73, Unnamed: 74]
Index: []

[0 rows x 75 columns]

In [6]:
db[db["field_sample_id"].duplicated()]

,field_sample_id,ArchiveSamplingDate,ArchiveSamplingSubmitter,ArchiveSamplingSubmissionDate
616,CGG_3_017493,2023-10-17 00:00:00.000,AR,2023-10-17 00:00:00.000

In [7]:
merged[merged["CGG ID"].duplicated()]

,CGG ID,Museum ID/sample ID,Lab no.,Stock sample left,Extraction#,Extraction date,Kind of Library,Library date,Intern Provider,Sample type,...,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,ArchiveSamplingDate,ArchiveSamplingSubmitter,ArchiveSamplingSubmissionDate
236,CGG_3_017493,T1B 50.5,T1B 50.5,No,NaN,NaN,NaN,NaN,Wesley Randall Farnsworth - RH <wesleyf@hi.is>,lake core,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-10-17 00:00:00.000,AR,2023-10-17 00:00:00.000

In [8]:
# for pro in merged["Intern Provider"].unique():
    

#     pro_f = str(pro).strip().replace(" ", "_")
#     pro_f = re.sub(r'[^A-Za-z0-9]+', '_', pro_f)
#     merged[merged["Intern Provider"].apply(str) == str(pro)].to_csv(index=False, path_or_buf=rf"c:\Users\glj523\Downloads\{pro_f}.tsv", sep="\t", encoding='utf-8')

In [9]:
for id in merged["ArchiveSamplingSubmitter"].unique():
    merged[merged["ArchiveSamplingSubmitter"].apply(str) == str(id)].to_csv(index=False, path_or_buf=rf"c:\Users\glj523\Downloads\{id}.tsv", sep="\t", encoding='utf-8')

In [13]:
cgg["Intern Provider"].dropna()[cgg["Intern Provider"].dropna().str.startswith('Astrid')]

3489    Astrid Schmidt
3490    Astrid Schmidt
3492    Astrid Schmidt
3494    Astrid Schmidt
3496    Astrid Schmidt
3498    Astrid Schmidt
3499    Astrid Schmidt
3500    Astrid Schmidt
3501    Astrid Schmidt
3502    Astrid Schmidt
3503    Astrid Schmidt
3504    Astrid Schmidt
3505    Astrid Schmidt
3506    Astrid Schmidt
3507    Astrid Schmidt
3508    Astrid Schmidt
3509    Astrid Schmidt
3510    Astrid Schmidt
3511    Astrid Schmidt
3512    Astrid Schmidt
3513    Astrid Schmidt
3514    Astrid Schmidt
3515    Astrid Schmidt
3516    Astrid Schmidt
Name: Intern Provider, dtype: object